script_history_0000:
    gameText("Durante a batalha letal")
 newline()
    gameText("contra Vegeta,")
 newline()
    gameText("Goku e os guerreiros Z")
 newline()
    gameText("fizeram dolorosos")
 newline()
    gameText("sacrifícios...")
 newline()
 paragraph()
 newline()
    gameText("Com o o objetivo")
 newline()
    gameText("de ressucitar seus")
 newline()
    gameText("preciosos companheiros")
 newline()
    gameText("usando as Esferas do Dragão,")
 newpage()


    gameText("Gohan e os outros")
 newline()
    gameText("seguiram em direção")
 newline()
    gameText("à Terra Natal de")
 newline()
    gameText("Piccolo: o planeta")
 newline()
    gameText("Namekusei.")
 newline()
 paragraph()
 newline()
    gameText("Entretanto, Freeza já")
 newline()
    gameText("tinha iniciado sua")
 newline()
    gameText("buscas pelas")
 newline()
    gameText("Esferas do Dragão.")
 newpage()


    gameText("Gohan e o outros")
 newline()
    gameText("foram forçados à")
 newline()
    gameText("enfrentar Freeza e")
 newline()
    gameText("Vegeta, e usar as")
 newline()
    gameText("Esferas do Dragão")
 newline()
 paragraph()
    gameText("para ressucitar Porunga.")
 newline()
    gameText("E desejar que Piccolo")
 newline()
    gameText("fosse teletransportado")
 newline()
    gameText("para o planeta Namekusei.")
 newpage()

 newline()
    gameText("Após chegar no planeta,")
 newline()
    gameText("Piccolo fundiu-se")
 newline()
    gameText("com um Namekuseijin")
 newline()
    gameText("chamado Nail")
 newline()
 paragraph()
    gameText("e obteve um poder")
 newline()
    gameText("bem mais elevado")
 newline()
    gameText("que o que possuia.")
 endstring()


script_history_0001:
    gameText("Então inciou-se a")
 newline()
    gameText("batalha de Piccolo")
 newline()
    gameText("e Freeza, agora em sua")
 newline()
    gameText("forma final.")
 endstring()


script_history_0002:
    gameText("Miserável! Farei você")
 newline()
    gameText("sentir o ódio de todos")
 newline()
    gameText("os Namekuseijins que")
 newline()
    gameText("você assassinou!")
 endstring()


script_history_0003:
    gameText("Antes matarei você,")
 newline()
    gameText("deixe-me mostrar")
 newline()
    gameText("meu poder máximo")
 newline()
    gameText("em minha forma final.")
 newpage()


    gameText("Dizem que ele é mais")
 newline()
    gameText("assustador que a")
 newline()
    gameText("própria morte")
 newline()
    gameText("em si.")
 endstring()


script_history_0004:
 newline()
    gameText("Kukkukku...")
 newline()
 newline()
 newline()
 newpage()


    gameText("Eu fui descuidado")
 newline()
    gameText("no passado...")
 newline()
    gameText("E acabei por")
 newline()
    gameText("subestimar você...")
 newpage()


 newline()
    gameText("Você é bem mais capaz")
 newline()
    gameText("do que eu havia")
 newline()
    gameText("imaginado...")
 newpage()


 newline()
    gameText("Pois bem, deixe-me")
 newline()
    gameText("mostrar MEU poder")
 newline()
    gameText("como se deve!")
 endstring()


script_history_0005:
 newline()
    gameText("M-M-Maldição...")
 newline()
 newline()
 newpage()


    gameText("Depois de todo os")
 newline()
    gameText("transtornos que eles")
 newline()
    gameText("passaram para conseguir")
 newline()
    gameText("as Esferas do Dragão")
 newline()
    gameText("e me trazer de volta...")
 newpage()


    gameText("Desculpem-me, amigos...")
 newline()
    gameText("parece que não vou")
 newline()
    gameText("conseguir fazer muito")
 newline()
    gameText("para ajudar vocês.")
 endstring()


script_history_0006:
    gameText("Durante a batalha,")
 newline()
    gameText("Piccolo e os ")
 newline()
    gameText("guerreiros Z pareciam")
 newline()
    gameText("ser superiores.")
 newline()
 newline()
 paragraph()
    gameText("Entretanto, o poder")
 newline()
    gameText("de batalha de Freeza")
 newline()
    gameText("aparentava vir de")
 newline()
    gameText("outro plano além")
 newline()
    gameText("da existencia. ")
 newpage()


    gameText("Os Guerreiros Z")
 newline()
    gameText("não poderiam dar")
 newline()
    gameText("nenhum passo em falso.")
 newline()
 newline()
    gameText("No calor da batalha,")
 newline()
 paragraph()
    gameText("a silhueta de Goku")
 newline()
    gameText("totalmente recuperado")
 newline()
    gameText("apareceu na frente de")
 newline()
    gameText("Piccolo e os outros.")
 endstring()


script_history_0007:
    gameText("Embora Piccolo tivesse")
 newline()
    gameText("se fundido à Nail,")
 newline()
    gameText("ele não poderia fazer")
 newline()
    gameText("nada diante da forma")
 newline()
    gameText("final de Freeza.")
 newline()
 paragraph()
    gameText("No calor da batalha,")
 newline()
   gameText("a silhueta de Goku")
 newline()
    gameText("totalmente recuperado")
 newline()
    gameText("apareceu na frente de")
 newline()
    gameText("Piccolo e os outros.")
 endstring()


script_history_0008:
 newline()
 newline()
    gameText("Batalha Especial 1")
 newline()
 newline()
    gameText("Son Gohan")
 newline()
 paragraph()
    gameText("   V.S.")
 newline()
    gameText("Gotenks")
endstring()


script_history_0009:
 newline()
 newline()
    gameText("Batalha Especial 2")
 newline()
 newline()
    gameText("Son Goku")
 newline()
 paragraph()
    gameText("   V.S.")
 newline()
    gameText("Son Gohan")
endstring()


script_history_0010:
 newline()
 newline()
    gameText("Batalha Especial 2")
 newline()
 newline()
    gameText("Son Goku")
 newline()
 paragraph()
    gameText("   V.S.")
 newline()
    gameText("Son Gohan")
endstring()


script_history_0011:
 newline()
 newline()
    gameText("Batalha Final")
 newline()
 newline()
    gameText("Son Gohan")
 newline()
 paragraph()
    gameText("   V.S.")
 newline()
    gameText("Vegetto")
endstring()
     
     
     script_history_0012:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


 newline()
    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
 paragraph()
    gameText("que Freeza resolveu")
 newline()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0013:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


 newline()
    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
 paragraph()
    gameText("que Freeza resolveu")
 newline()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0014:
    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
    gameText("que Freeza resolveu")
 newline()
 paragraph()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0015:
    gameText("Goku ficou furioso")
 newline()
    gameText("com a morte de Kuririn.")
 newline()
    gameText("E o Super Saiyajin")
 newline()
    gameText("despertou dentro nele.")
 endstring()


script_history_0016:
    gameText("Eu sou um Saiyajin")
 newline()
    gameText("que cresceu no Planeta")
 newline()
    gameText("Terra! Para me vingar")
 newline()
    gameText("de todos os Saijajins")
 newline()
    gameText("e Namukuseijins que ")
 newpage()


    gameText("você teve a ousadia")
 newline()
    gameText("de assassinar. Eu vou")
 newline()
    gameText("destruir você!")
 endstring()


script_history_0017:
    gameText("Que absurdo")
 newline()
    gameText("total é esse...")
 endstring()


script_history_0018:
 newline()
    gameText(".........")
 endstring()


script_history_0019:
 newline()
 newline()
    gameText("Goku derrotou Freeza.")
 newline()
    gameText("E os Guerreiros Z que")
 newline()
    gameText("estavam mortos foram")
 newline()
 paragraph()
    gameText("ressucitados por Porunga,")
 newline()
    gameText("já Goku continuou seu")
 newline()
    gameText("treinamento no espaço.")
 newline()
 newpage()


    gameText("Um ano após, Freeza")
 newline()
    gameText("totalmente transformado")
 newline()
    gameText("em um ciborg,")
 newline()
    gameText("foi em direção ao")
 newline()
    gameText("planeta Terra.")
 newline()
 paragraph()
 newline()
    gameText("Entretanto, Freeza foi")
 newline()
    gameText("rapidamente eliminado")
 newline()
    gameText("por um único Saiyajin")
 newline()
    gameText("portando uma espada.")
 newpage()


    gameText("Esse jovem Saiyajin era")
 newline()
    gameText("conhecido como Trunks.")
 newline()
 newline()
    gameText("Trunks veio de um futuro")
 newline()
    gameText("desastroso aonde as")
 newline()
 paragraph()
    gameText("maquinas, conhecidas")
 newline()
    gameText("como: ((QUOleft)Androids(QUOright)")
 newline()
    gameText("todos foram assassinados")
 newline()
    gameText("assim que elas apareceram")
 newline()
    gameText("causando morte e destruição.")
 newline()
 newpage()


    gameText("A chegada de Trunks")
 newline()
    gameText("com certeza havia")
 newline()
    gameText("modificado o futuro.")
 newline()
 newline()
    gameText("Isso ficou evidente")
 newline()
 paragraph()
    gameText("pelo surgimento de Cell,")
 newline()
    gameText("um andróide tão poderoso")
 newline()
    gameText("que ultrapassará")
 newline()
    gameText("tudo que exisitia na")
 newline()
    gameText("imaginação de Trunks.")
 endstring()


script_history_0020:
    gameText("Cell absorveu muitos")
 newline()
    gameText("humanos e também os Números")
 newline()
    gameText("17 e 18. Adquirindo")
 newline()
    gameText("sua forma perfeita.")
 endstring()


script_history_0021:
 newline()
    gameText("Entretanto, após")
 newline()
    gameText("alcançar seu corpo")
 newline()
    gameText("perfeito, Cell foi")
 newline()
    gameText("confrontado por um")
 newline()
 paragraph()
    gameText("guerreiro que ainda")
 newline()
    gameText("não havia feito sua")
 newline()
    gameText("estréia na batalha.")
 newline()
 newpage()


 newline()
 newline()
    gameText("Ele era Vegeta, que")
 newline()
    gameText("após um treinamento")
 newline()
    gameText("intensivo conseguir poder")
 newline()
 paragraph()
    gameText("suficiente para transformar-se")
 newline()
    gameText("em Super Saiyajin.")
 endstring()


script_history_0022:
    gameText("Então você gosta de")
 newline()
    gameText("atormentar a vida desses")
 newline()
    gameText("vermes insignificantes,")
 newline()
    gameText("não é?")
 newpage()


    gameText("Parece que você finalmente")
 newline()
    gameText("conseguiu a tão desejada")
 newline()
    gameText("((QUOleft)Forma Perfeita(QUOright),")
 newline()
    gameText("e nada vai ficar")
 newpage()


    gameText("no seu caminho,")
 newline()
    gameText("hein?")
 endstring()


script_history_0023:
 newline()
    gameText("Você é um pedra no")
 newline()
    gameText("sapato...")
 newline()
 newline()
 newpage()


 newline()
    gameText("Bem, vamos ver se")
 newline()
    gameText("você ao menos consegue")
 newline()
    gameText("me da um pouco de diversão?")
 endstring()


script_history_0024:
    gameText("N-Não pode ser!")
 newline()
    gameText("I-...Im-...Impossível!")
 newline()
    gameText("Meu corpo estava")
 newline()
    gameText("finalmente perfeito...")
 newpage()


 newline()
    gameText("Maldição!")
 newline()
 newline()
 newpage()


 newline()
    gameText("Brincadeirinha!")
 endstring()


script_history_0025:
    gameText("Hehehe...")
 newline()
    gameText("Você é teimoso, hein?")
 newline()
    gameText("Parece que você insiste")
 newline()
    gameText("em continuar vivo...")
 endstring()


script_history_0026:
    gameText("Mesmo com o poder")
 newline()
    gameText("de um Super Saiyajin,")
 newline()
    gameText("o ataque de Vegeta")
 newline()
    gameText("não chegou nem perto")
 newline()
    gameText("de fazer um arranhão em")
 newline()
 paragraph()
    gameText("Cell.")
 newline()
 newline()
    gameText("Enquanto os outros")
 newline()
    gameText("guerreiros aumentavam")
 newline()
    gameText("seus poderes, Cell")
 newpage()
    gameText("informou que os seus")
 newline()
    gameText("jogos iniciaram-se")
 newline()
    gameText("em um período de")
 newline()
    gameText("dez dias.")
 newline()
 newline()
 paragraph()
    gameText("Cell apenas fez isso")
 newline()
    gameText("para aumentar o terror")
 newline()
    gameText("no coração da humanidade,")
 newline()
    gameText("ele queria ver o medo")
 newline()
    gameText("crescendo em seus olhos.")
 newpage()


    gameText("Goku e os Guerreiros Z")
 newline()
    gameText("montaram uma estratégia")
 newline()
    gameText("e treinaram intensivamente")
 newline()
    gameText("para confromtar")
 newline()
    gameText("Cell em seus jogos.")
 newline()
 paragraph()
 newline()
    gameText("E no período de dez dias,")
 newline()
    gameText("o fatídico dia chegou.")
 endstring()


script_history_0027:
    gameText("Mesmo com o poder")
 newline()
    gameText("de um Super Saiyajin,")
 newline()
    gameText("o ataque de Vegeta")
 newline()
    gameText("não chegou nem perto")
 newline()
    gameText("de fazer um arranhão em")
 newline()
 paragraph()
    gameText("Cell.")
 newline()
 newline()
    gameText("Enquanto os outros")
 newline()
    gameText("guerreiros aumentavam")
 newline()
    gameText("seus poderes, Cell")
 newpage()
   gameText("informou que os seus")
 newline()
    gameText("jogos iniciaram-se")
 newline()
    gameText("em um período de")
 newline()
    gameText("dez dias.")
 newline()
 newline()
 paragraph()
    gameText("Cell apenas fez isso")
 newline()
    gameText("para aumentar o terror")
 newline()
    gameText("no coração da humanidade,")
 newline()
    gameText("ele queria ver o medo")
 newline()
    gameText("crescendo em seus olhos.")
 newpage()


    gameText("Goku e os Guerreiros Z")
 newline()
    gameText("montaram uma estratégia")
 newline()
    gameText("e treinaram intensivamente")
 newline()
    gameText("para confromtar")
 newline()
    gameText("Cell em seus jogos.")
 newline()
 paragraph()
 newline()
    gameText("E no período de dez dias,")
 newline()
    gameText("o fatídico dia chegou.")
 endstring()


script_history_0028:
    gameText("Muito bem!")
 newline()
    gameText("O que vocês me")
 newline()
    gameText("dizem de iniciarmos")
 newline()
    gameText("nossa batalha?!")
 endstring()


script_history_0029:
 newline()
    gameText("Então, vamos começar")
 newline()
    gameText("com você, o que acha?")
 newline()
 newpage()


    gameText("Embora eu deva admitir")
 newline()
    gameText("que eu estava ansioso")
 newline()
    gameText("para lutar com você,")
 newline()
    gameText("eu prefiro deixar")
 newpage()


    gameText("você por ultimo...")
 endstring()


script_history_0030:
 newline()
    gameText("Eu Desisto! Você venceu!")
 newline()
    gameText("Agora eu vi que você")
 newline()
    gameText("é extremamente poderoso!")
 newpage()


 newline()
    gameText("Já estou exausto.")
 endstring()


script_history_0031:
    gameText("Goku já havia desistido")
 newline()
    gameText("e Gohan era o próximo")
 newline()
    gameText("a ser desafiado")
 newline()
    gameText("por Cell.")
 newline()
 newline()
 paragraph()
    gameText("Entretanto, Cell não")
 newline()
    gameText("seria páreo para Gohan")
 newline()
    gameText("após este liberar seu")
 newline()
    gameText("verdadeiro poder.")
 endstring()


script_history_0032:
    gameText("Cell tentou se auto")
 newline()
    gameText("destruir mas Goku deu")
 newline()
    gameText("sua própria vida para")
 newline()
    gameText("salvar seus amigos.")
 newline()
 newline()
 paragraph()
    gameText("Enquanto todos lamentavam")
 newline()
    gameText("a perda de Goku, Cell")
 newline()
    gameText("reviveu em sua")
 newline()
    gameText("forma Perfeita!")
 newpage()


    gameText("Porém, Cell logo")
 newline()
    gameText("conheceria o Kamehameha")
 newline()
    gameText("Final de Gohan.")
 newline()
 newline()
    gameText("Um dos braços de Gohan's")
 newline()
 paragraph()
    gameText("estava incapacitado, mas")
 newline()
    gameText("com o poder de Goku's")
 newline()
    gameText("auxiliando-o,")
 newline()
    gameText("Gohan conseguiu elevar")
 newpage()


    gameText("seu poderoso ki")
 newline()
    gameText("uma última vez.")
 newline()
 newline()
    gameText("A luta contra Cell")
 newline()
    gameText("finalmente havia")
 newline()
 paragraph()
    gameText("terminado.")
 newline()
 newpage()


    gameText("Anos se passaram após")
 newline()
    gameText("o fim da batalha contra")
 newline()
    gameText("Cell, e um novo Torneio")
 newline()
    gameText("de Artes Marciais")
 newline()
    gameText("iria começar em")
 newline()
 paragraph()
    gameText("breve, uma oportunidade")
 newline()
    gameText("para rever os velhos")
 newline()
    gameText("amigos.")
 newpage()


    gameText("Porém, um mago")
 newline()
    gameText("demoníaco trabalhava")
 newline()
    gameText("nas sombras para")
 newline()
    gameText("ressucitar o perigoso")
 newline()
    gameText("e temível Majin Buu.")
 newline()
 paragraph()
 newline()
    gameText("Goku for permitido")
 newline()
    gameText("à retornar para a Terra")
 newline()
    gameText("por apenas um dia. ")
 newpage()


    gameText("Mas, afim de evitar")
 newline()
    gameText("a ressurreição de Buu,")
 newline()
    gameText("ele foi com Vegeta e os")
 newline()
    gameText("outros impedir até")
 newline()
    gameText("o esconderijo de seu novo")
 newline()
 paragraph()
    gameText("inimigo.")
 newline()
 newline()
 endstring()


script_history_0033:
   gameText("Cell tentou se auto")
 newline()
    gameText("destruir mas Goku deu")
 newline()
    gameText("sua própria vida para")
 newline()
    gameText("salvar seus amigos.")
 newline()
 newline()
 paragraph()
    gameText("Enquanto todos lamentavam")
 newline()
    gameText("a perda de Goku, Cell")
 newline()
    gameText("reviveu em sua")
 newline()
    gameText("forma Perfeita!")
 newpage()


    gameText("Porém, Cell logo")
 newline()
    gameText("conheceria o Kamehameha")
 newline()
    gameText("Final de Gohan.")
 newline()
 newline()
    gameText("Um dos braços de Gohan's")
 newline()
 paragraph()
    gameText("estava incapacitado, mas")
 newline()
    gameText("com o poder de Goku's")
 newline()
    gameText("auxiliando-o,")
 newline()
    gameText("Gohan conseguiu elevar")
 newpage()
    gameText("seu poderoso ki")
 newline()
    gameText("uma última vez.")
 newline()
 newline()
    gameText("At last, the fight with")
 newline()
    gameText("Cell had come to")
 newline()
 paragraph()
    gameText("an end.")
 newline()
 newpage()


 newline()
    gameText("Anos se passaram após")
 newline()
    gameText("o fim da batalha contra")
 newline()
    gameText("Cell, e um novo Torneio")
 newline()
    gameText("de Artes Marciais")
 newline()
    gameText("iria começar em")
 newline()
 paragraph()
    gameText("breve, uma oportunidade")
 newline()
    gameText("para rever os velhos")
 newline()
    gameText("amigos.")
 newpage()


    gameText("Porém, um mago")
 newline()
    gameText("demoníaco trabalhava")
 newline()
    gameText("nas sombras para")
 newline()
    gameText("ressucitar o perigoso")
 newline()
    gameText("e temível Majin Buu.")
 newline()
 paragraph()
 newline()
    gameText("Goku for permitido")
 newline()
    gameText("à retornar para a Terra")
 newline()
    gameText("por apenas um dia. ")
 newpage()


 newline()
 newline()
    gameText("Mas, afim de evitar")
 newline()
    gameText("a ressurreição de Buu,")
 newline()
    gameText("ele foi com Vegeta e os")
 newline()
 paragraph()
    gameText("outros impedir até")
 newline()
    gameText("o esconderijo de seu novo")
 newline()
    gameText("inimigo.")
 endstring()


script_history_0034:
    gameText("Vegeta foi transformado")
 newline()
    gameText("em um guerreiro malígno")
 newline()
    gameText("por Babidi. Assim ele")
 newline()
    gameText("enfrentou Goku em batalha.")
 endstring()


script_history_0035:
    gameText("Usando meu poder")
 newline()
    gameText("supremo, Eu vou dar")
 newline()
    gameText("um fim nisso!")
 endstring()


script_history_0036:
 newline()
    gameText("Usando meu poder")
 newline()
    gameText("supremo, Eu vou dar")
 newline()
    gameText("um fim nisso!")
 endstring()


script_history_0037:
    gameText("Vamos lá!")
 newline()
    gameText("Estou doido para")
 newline()
    gameText("matar você, Kakarotto!")
 endstring()


script_history_0038:
    gameText("A batalhe entre Goku e")
 newline()
    gameText("Vegeta liberou uma energia")
 newline()
    gameText("nunca antes vista!")
 newline()
    gameText("Assim Majin Buu foi revivido.")
 endstring()


script_history_0039:
    gameText("Vamos deixar nossa")
 newline()
    gameText("batalha de lado por")
 newline()
    gameText("enquanto, sua atenção")
 newline()
    gameText("está em outro lugar.")
 newline()
 newpage()


 newline()
    gameText("Parece que você está")
 newline()
    gameText("mais focado no Majin Buu.")
 endstring()


script_history_0040:
    gameText("Já que eu seou o culpado")
 newline()
    gameText("dele estar aqui, eu mesmo")
 newline()
    gameText("vou cuidar do")
 newline()
    gameText("Majin Buu.")
 newline()
 newpage()


    gameText("A conclusão da nossa batalha")
 newline()
    gameText("vai ter que esperar")
 newline()
    gameText("um pouco enquanto eu")
 newline()
    gameText("lido com esse problema.")
 newpage()


    gameText("Desde que eu viva para")
 newline()
    gameText("terminar isso...")
 endstring()


script_history_0041:
 newline()
 newline()
    gameText("Impossibilitado de")
 newline()
    gameText("ignorar seus sentimentos")
 newline()
    gameText("por sua família, Vegeta")
 newline()
 paragraph()
    gameText("foi sozinho batalhar contra")
 newline()
    gameText("Majin Buu.")
 newline()
 newpage()


 newline()
 newline()
    gameText("Por ser a primeira vez")
 newline()
    gameText("que Vegeta lutava por")
 newline()
    gameText("alguém que não fosse")
 newline()
 paragraph()
    gameText("ele mesmo. Ele tinha")
 newline()
    gameText("forças para lutar com")
 newline()
    gameText("determinação.")
 newline()
 endstring()


script_history_0042:
    gameText("Esse imbecil horroso")
 newline()
    gameText("que é o Majin Buu?")
 newline()
    gameText("Eu não irei pro infeno")
 newline()
    gameText("sozinho!")
 newpage()


 newline()
    gameText("Eu vou levar você")
 newline()
    gameText("comigo, verme!")
 endstring()


script_history_0043:
 newline()
    gameText("Você me irritou!")
 newline()
    gameText("Mrrrrgh!")
 newline()
    gameText("Eu vou matar você!")
 endstring()


script_history_0044:
    gameText("Eu vou derrotar você:")
 newline()
    gameText("Vou fazer você explodir")
 newline()
    gameText("em mil pedacinhos, ao")
 newline()
    gameText("ponto de você não")
 newline()
 newpage()


    gameText("conseguir se regenerar!")
 newpage()


 newline()
    gameText("Essa é minha despedida...")
 newline()
    gameText("Bulma...")
 newline()
    gameText("Trunks...")
 newline()
 newpage()


 newline()
    gameText("e para você,")
 newline()
    gameText("Kakarotto...")
 endstring()


script_history_0045:
 newline()
    gameText("Vegeta deu sua vida")
 newline()
    gameText("para destruir Majin Buu.")
 newline()
    gameText("Porém, o ataque em que")
 newline()
    gameText("Vegeta apostou sua vida")
 newline()
 paragraph()
    gameText("não foi suficiente. Majin")
 newline()
    gameText("Buu facilmente regenerou-se")
 newline()
    gameText("novamente.")
 newline()
 newpage()


 newline()
    gameText("Para manter a capital")
 newline()
    gameText("do Oeste livre da")
 newline()
    gameText("destruição, Goku")
 newline()
    gameText("desafiou Majin Buu")
 newline()
 paragraph()
    gameText("e seu poder desconhecido")
 newline()
    gameText("para uma luta")
 newline()
    gameText("novamente.")
 endstring()


script_history_0046:
 newline()
    gameText("Vegeta e eu")
 newline()
    gameText("subestimamos")
 newline()
    gameText("muito você!")
 newline()
 newline()
 newpage()


    gameText("Até agora,")
 newline()
    gameText("pensei que seria")
 newline()
    gameText("impossível que Majin Buu")
 newline()
    gameText("fosse tão forte assim.")
 endstring()


script_history_0047:
    gameText("Eu vou matar você!")
 newline()
    gameText("Eu odeio caras como você,")
 newline()
    gameText("agindo como se fossem os")
 newline()
    gameText("bonzinhos! Mrrrrgh!")
 endstring()


script_history_0048:
    gameText("Você é incrível...")
 newline()
    gameText("Surpreendente!")
 newline()
    gameText("Você parece ser um")
 newline()
    gameText("verdadeiro idiota, mas...")
 newpage()


    gameText("Você é genial!")
 newline()
    gameText("Você pode ver perfeitamente")
 newline()
    gameText("todos os movimentos dos")
 newline()
    gameText("seus oponentes.")
 newpage()


 newline()
    gameText("Você vê os meus ")
 newline()
    gameText("completamente também,")
 newline()
    gameText("mas como?!")
 endstring()


script_history_0049:
 newline()
    gameText("Satan foi capaz de")
 newline()
    gameText("persuadir Majin Buu à")
 newline()
    gameText("acalmar-se por um curto")
 newline()
    gameText("período de tempo.")
 newline()
 paragraph()
 newline()
    gameText("Mas o espírito de vilão")
 newline()
    gameText("dentro dele já havia se")
 newline()
    gameText("transformado em Super Buu.")
 newpage()


    gameText("Piccolo, Gohan, e")
 newline()
    gameText("Gotenks foram absorvidos")
 newline()
    gameText("por Buu e ele ganhou")
 newline()
    gameText("mais poder ainda.")
 newline()
 newline()
 paragraph()
    gameText("Goku foi absorvido")
 newline()
    gameText("para dentro do corpo de")
 newline()
    gameText("Super Buu propositalmente")
 newline()
    gameText("afim de salvar Gohan")
 newline()
    gameText("e os outros, mas...")
 newline()
 endstring()


script_history_0050:
    gameText("Por conta disso o mal")
 newline()
    gameText("dentro de Majin Buu foi")
 newline()
    gameText("expelido, e um novo, Buu")
 newline()
    gameText("completamente mal nasceu.")
 endstring()


script_history_0051:
 newline()
    gameText("Após Buu ser eliminado")
 newline()
    gameText("da Terra, ele chegou ao")
 newline()
    gameText("reino dos Kaiooshin.")
 newline()
    gameText("Colocando todo à")
 newline()
 paragraph()
    gameText("existência cósmica em")
 newline()
    gameText("perigo, Goku iniciava")
 newline()
    gameText("a batalha final decisiva.")
 endstring()


script_history_0052:
    gameText("Muito bem!")
 newline()
    gameText("Vou ter que usar")
 newline()
    gameText("todo meu poder para")
 newline()
    gameText("vencer você!")
 newline()
 newpage()


 newline()
    gameText("Se formos derrotados aqui,")
 newline()
    gameText("todo universo será")
 newline()
    gameText("destruído...")
 endstring()


script_history_0053:
 newline()
    gameText("Hooooh!")
 newline()
    gameText("Uhoh uhoh!")
 newline()
    gameText("Whoahohohoh!")
 endstring()


script_history_0054:
    gameText("...Maldição...")
 newline()
    gameText("Sempre a mesma")
 newline()
    gameText("coisa, independente")
 newline()
    gameText("do que eu faça...")
 newpage()


 newline()
    gameText("Esse cara parece")
 newline()
    gameText("que nunca fica")
 newline()
    gameText("cansado...")
 endstring()


script_history_0055:
    gameText("Goku começou a reunir")
 newline()
    gameText("energia destruir")
 newline()
    gameText("Buu completamente.")
 newline()
    gameText("No entanto, ele precisava")
 newline()
    gameText("de tempo para reunir")
 newline()
 paragraph()
    gameText("o suficiente. Para dar")
 newline()
    gameText("o tempo que Goku")
 newline()
    gameText("necessitava, Vegeta arriscou")
 newline()
    gameText("sua própria vida em batalha.")
 endstring()


script_history_0056:
    gameText("Certo! O que você acha")
 newline()
    gameText("disso, verme-maldito?!")
 endstring()


script_history_0057:
    gameText("Gih!")
 endstring()


script_history_0058:
    gameText("Kakarotto...")
 newline()
    gameText("V-Você estava...")
 newline()
    gameText("realmente lutando...")
 newline()
    gameText("com esse imbecil!?")
 endstring()


script_history_0059:
    gameText("No momento em que")
 newline()
    gameText("aparentemente Vegeta")
 newline()
    gameText("seria morto, Mr.")
 newline()
    gameText("Satan valentemente")
 newline()
    gameText("desafiou Buu.")
 newline()
 paragraph()
    gameText("Sem saber o motivo, depois")
 newline()
    gameText("ouvir a voz de Satan, Buu")
 newline()
    gameText("viu-se angustiado e")
 newline()
    gameText("sentiu-se incapaz")
 newline()
    gameText("de atacar.")
 newpage()


 newline()
    gameText("Buu decidiu expelir")
 newline()
    gameText("aquela parte de si mesmo")
 newline()
    gameText("e então atacaou")
 newline()
    gameText("Satan, mais uma vez.")
 newline()
 paragraph()
    gameText("Porém, a parte expelida")
 newline()
    gameText("de Buu entrou na frente")
 newline()
    gameText("para proteger")
 newline()
    gameText("Satan.")
 endstring()


script_history_0060:
    gameText("Eu odeio você!")
 newline()
    gameText("Deixe o Satan em paz!")
 endstring()


script_history_0061:
    gameText("Kakkakaka...")
 newline()
    gameText("Hoohohohoh!")
 endstring()


script_history_0062:
    gameText("...Caramba...")
 newline()
    gameText("Eu não posso vencer!")
 endstring()


script_history_0063:
 newline()
 newline()
    gameText("Enqaunto Majin Buu")
 newline()
    gameText("batalhava, Vegeta teve")
 newline()
    gameText("a ideia de restaurar")
 newline()
 paragraph()
    gameText("a Terra e todos os")
 newline()
    gameText("Terráqueos assassinados.")
 newpage()


    gameText("Vegeta, Majin Buu, e")
 newline()
    gameText("também Satan...")
 newline()
 newline()
    gameText("Após receber a ajuda")
 newline()
    gameText("deles, Goku estava")
 newline()
 paragraph()
    gameText("pronto para coletar")
 newline()
    gameText("o Ki de todos")
 newline()
    gameText("transformando em uma")
 newline()
    gameText("Super Genki Dama.")
 endstring()


script_history_0064:
    gameText("Heh heh...")
 newline()
    gameText("Quanto mais perigoso")
 newline()
    gameText("isso parece,")
 newline()
    gameText("Mais eu fico animado!")
 endstring()


script_history_0065:
    gameText("Haaah!")
 endstring()


script_history_0066:
    gameText("Ufa...")
 newline()
    gameText("Finalmente...")
 newline()
    gameText("acabou...")
 endstring()


script_history_0067:
 newline()
 newline()
    gameText("Graças ao esforço de")
 newline()
    gameText("Goku e todos que")
 newline()
    gameText("ajudaram, Buu finalmente")
 newline()
 paragraph()
    gameText("foi destruído; nenhuma")
 newline()
    gameText("célula de seu corpo")
 newline()
    gameText("restou.")
 newline()
 newpage()


    gameText("E o mundo novamente")
 newline()
    gameText("poderá ficar em paz. Goku")
 newline()
    gameText("e seus amigos retornaram")
 newline()
    gameText("para suas residências")
 newline()
    gameText("e famílias. ")
 newline()
 paragraph()
 newline()
    gameText("Sim, eles retornaram ")
 newline()
    gameText("para nosso Planeta Terra...")
 newline()
 endstring()


script_history_0068:
    gameText("Goten, Trunks. Mostrem")
 newline()
    gameText("para Gohan o poder")
 newline()
    gameText("que você dois")
 newline()
    gameText("adquiriram!")
 endstring()


script_history_0069:
    gameText("Tadaaah!")
 newline()
    gameText("Deus da Morte")
 newline()
    gameText("e da Justiça,")
 newline()
    gameText("Supeeer Gotenks!")
 endstring()


script_history_0070:
 newline()
    gameText("Isso é incrível,")
 newline()
    gameText("Gohan!")
 newline()
 newline()
 newpage()


    gameText("O velho Kaioshin")
 newline()
    gameText("realmente despertou")
 newline()
    gameText("seu poder latente,")
 newline()
    gameText("hein?")
 newpage()


    gameText("Diga, Gohan!")
 newline()
    gameText("Gostaria de lutar")
 newline()
    gameText("comigo!?")
 endstring()


script_history_0071:
    gameText("Clarou! Contra você,")
 newline()
    gameText("papai, Eu posso lutar")
 newline()
    gameText("sem me segurar!")
 endstring()


script_history_0072:
 newline()
    gameText("Recentemente, Papai")
 newline()
    gameText("e Vegeta fundiram-se")
 newline()
    gameText("em um único ser.")
 newpage()


 newline()
    gameText("Eu adoraria lutar")
 newline()
    gameText("contra esse guerreiro")
 newline()
    gameText("chamado ((QUOleft)Vegetto(QUOright).")
 endstring()


script_history_0073:
    gameText("Vegeta e")
 newline()
    gameText("Kakarotto fundiram-se")
 newline()
    gameText("em um só...")
 newline()
 newpage()


    gameText("Suponho que agora eu")
 newline()
    gameText("seja Vegetto...")
 newline()
    gameText("Não, não apenas isso...")
 newline()
    gameText("Eu sou Super Vegetto!")
 endstring()


script_history_0074:
    gameText("Assim, a história de")
 newline()
    gameText("Goku, seus amigos e")
 newline()
    gameText("as Esféras do Dragão")
 newline()
    gameText("chegam ao fim.")
 newpage()


    gameText("No entanto, penso que")
 newline()
    gameText("Goku e seus amigos")
 newline()
    gameText("sempre terão novas")
 newline()
    gameText("histórias para começar")
 newline()
 newpage()


    gameText("em lugares distantes")
 newline()
    gameText("que nunca vimos.")
 newline()
 newline()
    gameText("Enquanto as Esféras")
 newline()
    gameText("do Dragão existirem...")
 endstring()


script_history_0075:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
    gameText("que Freeza resolveu")
 newline()
 paragraph()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0076:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
    gameText("que Freeza resolveu")
 newline()
 paragraph()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0077:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
    gameText("que Freeza resolveu")
 newline()
 paragraph()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()