script_history_0000:
    gameText("Durante a batalha letal")
 newline()
    gameText("contra Vegeta,")
 newline()
    gameText("Goku e os guerreiros Z")
 newline()
    gameText("fizeram dolorosos")
 newline()
    gameText("sacrifícios...")
 newline()
 paragraph()
 newline()
    gameText("Com o objetivo")
 newline()
    gameText("de ressucitar seus")
 newline()
    gameText("preciosos companheiros")
 newline()
    gameText("usando as Esferas do")
 newpage()


    gameText("Dragão, Gohan e os")
 newline()
    gameText("outros seguiram em")
 newline()
    gameText("direção à Terra Natal")
 newline()
    gameText("de Piccolo: o planeta")
 newline()
    gameText("Namekusei.")
 newline()
 paragraph()
 newline()
    gameText("Entretanto, Freeza já")
 newline()
    gameText("tinha iniciado sua")
 newline()
    gameText("buscas pelas")
 newline()
    gameText("Esferas do Dragão.")
 newpage()


    gameText("Gohan e o outros")
 newline()
    gameText("foram forçados à")
 newline()
    gameText("enfrentar Freeza e")
 newline()
    gameText("Vegeta, e usar as")
 newline()
    gameText("Esferas do Dragão")
 newline()
 paragraph()
    gameText("para ressucitar Porunga.")
 newline()
    gameText("E desejar que Piccolo")
 newline()
    gameText("fosse teletransportado")
 newline()
    gameText("para o planeta Namekusei.")
 newpage()

 newline()
    gameText("Após chegar no planeta,")
 newline()
    gameText("Piccolo fundiu-se")
 newline()
    gameText("com um Namekuseijin")
 newline()
    gameText("chamado Nail")
 newline()
 paragraph()
    gameText("e obteve um poder")
 newline()
    gameText("bem mais elevado")
 newline()
    gameText("do que possuia.")
 endstring()


script_history_0001:
    gameText("Então inciou-se a")
 newline()
    gameText("batalha de Piccolo")
 newline()
    gameText("e Freeza, agora em sua")
 newline()
    gameText("forma final.")
 endstring()


script_history_0002:
    gameText("Miserável! Farei você")
 newline()
    gameText("sentir o ódio de todos")
 newline()
    gameText("os Namekuseijins que")
 newline()
    gameText("você assassinou!")
 endstring()


script_history_0003:
    gameText("Antes vou matar você,")
 newline()
    gameText("deixe-me mostrar")
 newline()
    gameText("meu poder máximo")
 newline()
    gameText("em minha forma final.")
 newpage()


    gameText("Dizem que ela é")
 newline()
    gameText("mais assustadora")
 newline()
    gameText("que a própria morte.")
 newline()
    gameText("")
 endstring()


script_history_0004:
 newline()
    gameText("Kukkukku...")
 newline()
 newline()
 newline()
 newpage()


    gameText("Eu fui descuidado")
 newline()
    gameText("no passado...")
 newline()
    gameText("E acabei por")
 newline()
    gameText("subestimar você...")
 newpage()


 newline()
    gameText("Você é bem mais forte")
 newline()
    gameText("do que eu havia")
 newline()
    gameText("imaginado...")
 newpage()


 newline()
    gameText("Pois bem, deixe-me")
 newline()
    gameText("mostrar MEU verdadeiro")
 newline()
    gameText("poder!")
 endstring()


script_history_0005:
 newline()
    gameText("M-M-Maldição...")
 newline()
 newline()
 newpage()


    gameText("Depois de todo os")
 newline()
    gameText("transtornos que eles")
 newline()
    gameText("passaram para")
 newline()
    gameText("conseguir as Esferas")
 newline()
    gameText("do Dragão e me trazer")
 newline()
    gameText("de volta...")
 newpage()


    gameText("Desculpem-me, amigos...")
 newline()
    gameText("parece que não vou")
 newline()
    gameText("conseguir fazer muito")
 newline()
    gameText("para ajudar vocês.")
 endstring()


script_history_0006:
    gameText("Durante a batalha,")
 newline()
    gameText("Piccolo e os ")
 newline()
    gameText("guerreiros Z pareciam")
 newline()
    gameText("ser superiores.")
 newline()
 newline()
 paragraph()
    gameText("Entretanto, o poder")
 newline()
    gameText("de batalha de Freeza")
 newline()
    gameText("aparentava vir de")
 newline()
    gameText("outro plano além")
 newline()
    gameText("da existencia. ")
 newpage()


    gameText("Os Guerreiros Z")
 newline()
    gameText("não poderiam dar")
 newline()
    gameText("nenhum passo em falso.")
 newline()
 newline()
    gameText("No calor da batalha,")
 newline()
 paragraph()
    gameText("a silhueta de Goku")
 newline()
    gameText("totalmente recuperado")
 newline()
    gameText("apareceu na frente de")
 newline()
    gameText("Piccolo e os outros.")
 endstring()


script_history_0007:
    gameText("Embora Piccolo tivesse")
 newline()
    gameText("se fundido à Nail,")
 newline()
    gameText("ele não poderia fazer")
 newline()
    gameText("nada diante da forma")
 newline()
    gameText("final de Freeza.")
 newline()
 paragraph()
    gameText("No calor da batalha,")
 newline()
   gameText("a silhueta de Goku")
 newline()
    gameText("totalmente recuperado")
 newline()
    gameText("apareceu na frente de")
 newline()
    gameText("Piccolo e os outros.")
 endstring()


script_history_0008:
 newline()
 newline()
    gameText("        Batalha Especial 1")
 newline()
 newline()
    gameText("                 Son Gohan")
 newline()
 paragraph()
    gameText("                       V.S.")
 newline()
    gameText("                   Gotenks")
endstring()


script_history_0009:
 newline()
 newline()
    gameText("        Batalha Especial 2")
 newline()
 newline()
    gameText("                 Son Goku")
 newline()
 paragraph()
    gameText("                    V.S.")
 newline()
    gameText("                 Son Gohan")
endstring()


script_history_0010:
 newline()
 newline()
    gameText("        Batalha Especial 2")
 newline()
 newline()
    gameText("                  Son Goku")
 newline()
 paragraph()
    gameText("                       V.S.")
 newline()
    gameText("                 Son Gohan")
endstring()


script_history_0011:
 newline()
 newline()
    gameText("             Batalha Final")
 newline()
 newline()
    gameText("                 Son Gohan")
 newline()
 paragraph()
    gameText("                       V.S.")
 newline()
    gameText("                   Vegetto")
endstring()
     
     
     script_history_0012:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


 newline()
    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
 paragraph()
    gameText("que Freeza resolveu")
 newline()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0013:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


 newline()
    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
 paragraph()
    gameText("que Freeza resolveu")
 newline()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0014:
    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
    gameText("que Freeza resolveu")
 newline()
 paragraph()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0015:
    gameText("Goku ficou furioso")
 newline()
    gameText("com a morte de Kuririn.")
 newline()
    gameText("E o Super Saiyajin")
 newline()
    gameText("despertou dentro nele.")
 endstring()


script_history_0016:
    gameText("Eu sou um Saiyajin")
 newline()
    gameText("que cresceu no Planeta")
 newline()
    gameText("Terra! Para me vingar")
 newline()
    gameText("de todos os Saijajins")
 newline()
    gameText("e Namukuseijins que ")
 newpage()


    gameText("que você teve a")
 newline()
    gameText("ousadia de assassinar.")
 newline()
    gameText("Eu vou destruir você!")
 endstring()


script_history_0017:
    gameText("Que absurdo")
 newline()
    gameText("total é esse...")
 endstring()


script_history_0018:
 newline()
    gameText(".........")
 endstring()


script_history_0019:
 newline()
 newline()
    gameText("Goku derrotou Freeza.")
 newline()
    gameText("E os Guerreiros Z que")
 newline()
    gameText("estavam mortos foram")
 newline()
 paragraph()
    gameText("ressucitados por Porunga,")
 newline()
    gameText("já Goku continuou seu")
 newline()
    gameText("treinamento no espaço.")
 newline()
 newpage()


    gameText("Um ano após, Freeza")
 newline()
    gameText("totalmente transformado")
 newline()
    gameText("em um ciborg, foi em")
 newline()
    gameText("direção ao planeta Terra.")
 newline()
 paragraph()
 newline()
    gameText("Entretanto, Freeza foi")
 newline()
    gameText("rapidamente eliminado")
 newline()
    gameText("por um único Saiyajin")
 newline()
    gameText("portando uma espada.")
 newpage()


    gameText("Esse jovem Saiyajin era")
 newline()
    gameText("conhecido como Trunks.")
 newline()
 newline()
    gameText("Trunks veio de um futuro")
 newline()
    gameText("catastrófico aonde as")
 newline()
 paragraph()
    gameText("maquinas, conhecidas")
 newline()
    gameText("como Androids,")
 newline()
    gameText("assassinaram todos os")
 newline()
    gameText("Guerreiros Z, causando")
 newline()
    gameText("morte e destruição.")
 newline()
 newpage()


    gameText("A chegada de Trunks")
 newline()
    gameText("com certeza havia")
 newline()
    gameText("modificado o futuro.")
 newline()
 newline()
    gameText("Isso ficou evidente")
 newline()
 paragraph()
    gameText("pelo surgimento de Cell,")
 newline()
    gameText("um andróide tão poderoso")
 newline()
    gameText("que ultrapassou")
 newline()
    gameText("tudo que exisitia na")
 newline()
    gameText("imaginação de Trunks.")
 endstring()


script_history_0020:
    gameText("Cell absorveu muitos")
 newline()
    gameText("humanos e os Andróides 17")
 newline()
    gameText("e 18. Alcançando sua")
 newline()
    gameText("forma perfeita.")
 endstring()


script_history_0021:
 newline()
    gameText("Entretanto, após alcançar")
 newline()
    gameText("seu corpo perfeito, Cell")
 newline()
    gameText("foi confrontado por um")
 newline()
    gameText("guerreiro que ainda não")
 newline()
 paragraph()
    gameText("havia feito sua estréia")
 newline()
    gameText("na batalha.")
 newline()
    gameText("")
 newline()
 newpage()


 newline()
 newline()
    gameText("Ele era Vegeta, que")
 newline()
    gameText("após um treinamento")
 newline()
    gameText("intensivo conseguiu poder")
 newline()
 paragraph()
    gameText("suficiente para se")
 newline()
    gameText("transformar em")
 newline()
    gameText("Super Saiyajin.")
 endstring()


script_history_0022:
    gameText("Então você gosta de")
 newline()
    gameText("atormentar a vida")
 newline()
    gameText("desses vermes")
 newline()
    gameText("insignificantes, não é?")
 newpage()


    gameText("Parece que você")
 newline()
    gameText("finalmente conseguiu")
 newline()
    gameText("a tão desejada forma")
 newline()
    gameText("perfeita, e nada vai")
 newpage()
    gameText("ficar no seu caminho,")
 newline()
    gameText("hein?")
 endstring()


script_history_0023:
 newline()
    gameText("Você é uma pedra")
 newline()
    gameText("no sapato...")
 newline()
 newline()
 newpage()


 newline()
    gameText("Bem, vamos ver se")
 newline()
    gameText("você ao menos consegue")
 newline()
    gameText("me dar um pouco de")
 newpage()
 newline()
    gameText("diversão?")
 newline()
 newline()
 endstring()


script_history_0024:
    gameText("N-Não pode ser!")
 newline()
    gameText("I...Im...Impossível!")
 newline()
    gameText("Meu corpo estava")
 newline()
    gameText("finalmente perfeito...")
 newpage()


 newline()
    gameText("Maldição!")
 newline()
 newline()
 newpage()


 newline()
    gameText("Será que é isso")
 newline()
    gameText("mesmo!")
 endstring()


script_history_0025:
    gameText("Hehehe...")
 newline()
    gameText("Você é teimoso, hein?")
 newline()
    gameText("Parece que você insiste")
 newline()
    gameText("em continuar vivo...")
 endstring()


script_history_0026:
    gameText("Mesmo com o poder")
 newline()
    gameText("de um Super Saiyajin,")
 newline()
    gameText("o ataque de Vegeta")
 newline()
    gameText("não chegou nem perto")
 newline()
    gameText("de fazer um arranhão em")
 newline()
 paragraph()
    gameText("Cell.")
 newline()
 newline()
    gameText("Enquanto os outros")
 newline()
    gameText("guerreiros aumentavam")
 newline()
    gameText("seus poderes, Cell")
 newpage()
    gameText("informou que os seus")
 newline()
    gameText("jogos iriam se iniciar")
 newline()
    gameText("em um período de")
 newline()
    gameText("dez dias.")
 newline()
 newline()
 paragraph()
    gameText("Cell apenas fez isso")
 newline()
    gameText("para aumentar o terror")
 newline()
    gameText("no coração da humanidade,")
 newline()
    gameText("ele queria ver o medo")
 newline()
    gameText("crescendo em seus olhos.")
 newpage()


    gameText("Goku e os Guerreiros Z")
 newline()
    gameText("montaram uma estratégia")
 newline()
    gameText("e treinaram de forma")
 newline()
    gameText("intensa para confrontar")
 newline()
    gameText("Cell em seus jogos.")
 newline()
 paragraph()
 newline()
    gameText("E no período de dez dias,")
 newline()
    gameText("o fatídico dia chegou.")
 endstring()


script_history_0027:
    gameText("Mesmo com o poder")
 newline()
    gameText("de um Super Saiyajin,")
 newline()
    gameText("o ataque de Vegeta")
 newline()
    gameText("não chegou nem perto")
 newline()
    gameText("de fazer um arranhão em")
 newline()
 paragraph()
    gameText("Cell.")
 newline()
 newline()
    gameText("Enquanto os outros")
 newline()
    gameText("guerreiros aumentavam")
 newline()
    gameText("seus poderes, Cell")
 newpage()
   gameText("informou que os seus")
 newline()
    gameText("jogos iniciaram-se")
 newline()
    gameText("em um período de")
 newline()
    gameText("dez dias.")
 newline()
 newline()
 paragraph()
    gameText("Cell apenas fez isso")
 newline()
    gameText("para aumentar o terror")
 newline()
    gameText("no coração da humanidade,")
 newline()
    gameText("ele queria ver o medo")
 newline()
    gameText("crescendo em seus olhos.")
 newpage()


    gameText("Goku e os Guerreiros Z")
 newline()
    gameText("montaram uma estratégia")
 newline()
   gameText("e treinaram de forma")
 newline()
    gameText("intensa para confrontar")
 newline()
    gameText("Cell em seus jogos.")
 newline()
 paragraph()
 newline()
    gameText("E no período de dez dias,")
 newline()
    gameText("o fatídico dia chegou.")
 endstring()


script_history_0028:
    gameText("Muito bem!")
 newline()
    gameText("O que vocês me")
 newline()
    gameText("dizem de iniciarmos")
 newline()
    gameText("nossa batalha?!")
 endstring()


script_history_0029:
 newline()
    gameText("Então, vamos começar")
 newline()
    gameText("com você, o que acha?")
 newline()
 newpage()


    gameText("Embora eu deva admitir")
 newline()
    gameText("que eu estava ansioso")
 newline()
    gameText("para lutar com você,")
 newline()
    gameText("eu prefiro deixar")
 newpage()


    gameText("você por ultimo...")
 endstring()


script_history_0030:
 newline()
    gameText("Eu Desisto!")
 newline()
    gameText("Você venceu!")
 newline()
 newpage()

    gameText("Agora eu vi que você")
 newline()
    gameText("é extremamente")
 newline()
    gameText("poderoso!")
 newline()
    gameText("Já estou exausto.")
 endstring()


script_history_0031:
    gameText("Goku já havia desistido")
 newline()
    gameText("e Gohan era o próximo")
 newline()
    gameText("a ser desafiado por Cell.")
 newline()
    gameText("")
 newline()
 newline()
 paragraph()
    gameText("Entretanto, Cell não")
 newline()
    gameText("seria páreo para Gohan")
 newline()
    gameText("após este liberar seu")
 newline()
    gameText("verdadeiro poder.")
 endstring()


script_history_0032:
    gameText("Cell tentou se auto")
 newline()
    gameText("destruir mas Goku deu")
 newline()
    gameText("sua própria vida para")
 newline()
    gameText("salvar seus amigos.")
 newline()
 newline()
 paragraph()
    gameText("Enquanto todos")
 newline()
    gameText("lamentavam a perda")
 newline()
    gameText("de Goku, Cell reviveu")
 newline()
    gameText("em sua forma Perfeita!")
 newpage()


    gameText("Porém, Cell logo")
 newline()
    gameText("conheceria o Kamehameha")
 newline()
    gameText("Final de Gohan.")
 newline()
 newline()
    gameText("Um dos braços de Gohan")
 newline()
 paragraph()
    gameText("estava incapacitado, mas")
 newline()
    gameText("com o poder de Goku")
 newline()
    gameText("auxiliando-o,")
 newline()
    gameText("Gohan conseguiu elevar")
 newpage()


    gameText("seu poderoso ki uma")
 newline()
    gameText("última vez.")
 newline()
 newline()
    gameText("A luta contra Cell")
 newline()
    gameText("finalmente havia")
 newline()
 paragraph()
    gameText("terminado.")
 newline()
 newpage()


 newline()
    gameText("Anos se passaram após")
 newline()
    gameText("o fim da batalha contra")
 newline()
    gameText("Cell, e um novo Torneio")
 newline()
    gameText("de Artes Marciais iria")
 newline()
 paragraph()
    gameText("começar em breve,")
 newline()
    gameText("surgindo uma nova")
 newline()
    gameText("oportunidade para rever")
 newline()
    gameText("os velhos amigos.")
 newpage()


    gameText("Porém, um mago")
 newline()
    gameText("demoníaco trabalhava")
 newline()
    gameText("nas sombras para")
 newline()
    gameText("ressucitar o perigoso")
 newline()
    gameText("e temível Majin Boo.")
 newline()
 paragraph()
 newline()
    gameText("Goku for permitido")
 newline()
    gameText("à retornar para a Terra")
 newline()
    gameText("por apenas um dia. ")
 newpage()


    gameText(", afim de evitar")
 newline()
    gameText("a ressurreição de Boo,")
 newline()
    gameText("ele foi com Vegeta e os")
 newline()
    gameText("até o esconderijo de")
 newline()
 paragraph()
    gameText("seu novo inimigo.")
 newline()
 newline()
 newline()
 newline()
 endstring()


script_history_0033:
   gameText("Cell tentou se auto")
 newline()
    gameText("destruir mas Goku deu")
 newline()
    gameText("sua própria vida para")
 newline()
    gameText("salvar seus amigos.")
 newline()
 newline()
 paragraph()
    gameText("Enquanto todos")
 newline()
    gameText("lamentavam a perda")
 newline()
    gameText("de Goku, Cell reviveu")
 newline()
    gameText("em sua forma Perfeita!")
 newpage()


    gameText("Porém, Cell logo")
 newline()
    gameText("conheceria o Kamehameha")
 newline()
    gameText("Final de Gohan.")
 newline()
 newline()
    gameText("Um dos braços de Gohan")
 newline()
 paragraph()
    gameText("estava incapacitado, mas")
 newline()
    gameText("com o poder de Goku")
 newline()
    gameText("auxiliando-o,")
 newline()
    gameText("Gohan conseguiu elevar")
 newpage()


    gameText("seu poderoso ki uma")
 newline()
    gameText("última vez.")
 newline()
 newline()
    gameText("A luta contra Cell")
 newline()
    gameText("finalmente havia")
 newline()
 paragraph()
    gameText("terminado.")
 newline()
 newpage()


 newline()
    gameText("Anos se passaram após")
 newline()
    gameText("o fim da batalha contra")
 newline()
    gameText("Cell, e um novo Torneio")
 newline()
    gameText("de Artes Marciais iria")
 newline()
 paragraph()
    gameText("começar em breve,")
 newline()
    gameText("surgindo uma nova")
 newline()
    gameText("oportunidade para rever")
 newline()
    gameText("os velhos amigos.")
 newpage()


    gameText("Porém, um mago")
 newline()
    gameText("demoníaco trabalhava")
 newline()
    gameText("nas sombras para")
 newline()
    gameText("ressucitar o perigoso")
 newline()
    gameText("e temível Majin Boo.")
 newline()
 paragraph()
 newline()
    gameText("Foi permitido à Goku")
 newline()
    gameText("retornar para a Terra")
 newline()
    gameText("por apenas um dia. ")
 newpage()


 newline()
    gameText("Mas, afim de evitar a")
 newline()
    gameText("ressurreição de Boo,")
 newline()
    gameText("ele foi com Vegeta e os")
 newline()
    gameText("outros até o esconderijo")
 newline()
 paragraph()
    gameText("do seu novo inimigo.")
 newline()
 newline()
 newline()
 newline()
 newline()
 endstring()


 newline()
    gameText("Mas, afim de evitar a")
 newline()
    gameText("ressurreição de Boo,")
 newline()
    gameText("ele foi com Vegeta e os")
 newline()
    gameText("outros até o esconderijo")
 newline()
 paragraph()
    gameText("do seu novo inimigo.")
 newline()
 newline()
 newline()
 newline()
 newline()
 endstring()


script_history_0034:
    gameText("Vegeta foi transformado")
 newline()
    gameText("em um guerreiro malígno")
 newline()
    gameText("por Babidi. Então ele")
 newline()
    gameText("desafiou Goku!")
 endstring()


script_history_0035:
    gameText("Usando meu poder")
 newline()
    gameText("supremo, Eu vou dar")
 newline()
    gameText("um fim nisso!")
 endstring()


script_history_0036:
 newline()
    gameText("Usando meu poder")
 newline()
    gameText("supremo, Eu vou dar")
 newline()
    gameText("um fim nisso!")
 endstring()


script_history_0037:
    gameText("Vamos lá!")
 newline()
    gameText("Estou doido para")
 newline()
    gameText("matar você, Kakarotto!")
 endstring()


script_history_0038:
    gameText("A luta entre Goku e Vegeta")
 newline()
    gameText("liberou uma energia nunca")
 newline()
    gameText("antes vista! E Assim")
 newline()
    gameText("Majin Boo foi revivido.")
 endstring()


script_history_0039:
    gameText("Vamos deixar nossa")
 newline()
    gameText("batalha de lado por")
 newline()
    gameText("enquanto, sua atenção")
 newline()
    gameText("está em outro lugar.")
 newline()
 newpage()


 newline()
    gameText("Parece que você")
 newline()
    gameText("está mais focado")
 newline()
    gameText("no Majin Boo.")
 newline()
 endstring()


script_history_0040:
    gameText("Já que eu sou o")
 newline()
    gameText("culpado dele estar")
 newline()
    gameText("aqui, eu mesmo vou")
 newline()
    gameText("cuidar do Majin Boo.")
 newline()
 newpage()


    gameText("A conclusão da nossa")
 newline()
    gameText("batalha vai ter que")
 newline()
    gameText("esperar um pouco")
 newline()
    gameText("enquanto eu lido com")
 newline()
 newpage()
   gameText("esse problema.")
 newpage()

    gameText("Desde que eu viva para")
 newline()
    gameText("terminar isso...")
 endstring()


script_history_0041:
 newline()
 newline()
    gameText("Impossibilitado de")
 newline()
    gameText("ignorar seus sentimentos")
 newline()
    gameText("por sua família, Vegeta")
 newline()
 paragraph()
    gameText("foi sozinho enfrentar")
 newline()
    gameText("Majin Boo.")
 newline()
 newpage()


 newline()
 newline()
    gameText("Por ser a primeira vez")
 newline()
    gameText("que Vegeta lutava por")
 newline()
    gameText("alguém que não fosse")
 newline()
 paragraph()
    gameText("ele mesmo. Ele tinha")
 newline()
    gameText("forças para lutar com")
 newline()
    gameText("determinação.")
 newline()
 endstring()


script_history_0042:
    gameText("Esse imbecil horroso")
 newline()
    gameText("que é o Majin Boo?")
 newline()
    gameText("Eu não irei pro infeno")
 newline()
    gameText("sozinho!")
 newpage()


 newline()
    gameText("Eu vou levar você")
 newline()
    gameText("comigo, verme!")
 endstring()


script_history_0043:
 newline()
    gameText("Você me irritou!")
 newline()
    gameText("Mrrrrgh!")
 newline()
    gameText("Eu vou matar você!")
 endstring()


script_history_0044:
    gameText("Eu vou derrotar você:")
 newline()
    gameText("Vou fazer você explodir")
 newline()
    gameText("em mil pedacinhos, ao")
 newline()
    gameText("ponto de você não")
 newline()
 newpage()


    gameText("conseguir se regenerar!")
 newpage()


 newline()
    gameText("Essa é minha despedida...")
 newline()
    gameText("Bulma...")
 newline()
    gameText("Trunks...")
 newline()
 newpage()


 newline()
    gameText("...e para você,")
 newline()
    gameText("Kakarotto...")
 endstring()


script_history_0045:
 newline()
    gameText("Vegeta deu sua vida")
 newline()
    gameText("para destruir Majin Boo.")
 newline()
    gameText("Porém, o ataque em que")
 newline()
    gameText("Vegeta apostou sua vida")
 newline()
 paragraph()
    gameText("não foi suficiente.")
 newline()
    gameText("Majin Boo facilmente")
 newline()
    gameText("se regenerou novamente.")
 newline()
 newpage()


 newline()
    gameText("Para manter a capital")
 newline()
    gameText("do Oeste livre da")
 newline()
    gameText("destruição, Goku")
 newline()
    gameText("desafiou Majin Boo")
 newline()
 paragraph()
    gameText("e seu poder desconhecido")
 newline()
    gameText("para uma luta novamente.")
 newline()
 endstring()


script_history_0046:
 newline()
    gameText("Vegeta e eu")
 newline()
    gameText("subestimamos")
 newline()
    gameText("muito você!")
 newline()
 newline()
 newpage()


    gameText("Até agora, pensei")
 newline()
    gameText("que seria impossível")
 newline()
    gameText("que Majin Boo fosse")
 newline()
    gameText("tão forte assim.")
 endstring()


script_history_0047:
    gameText("Eu vou matar você!")
 newline()
    gameText("Eu odeio caras como")
 newline()
    gameText("você, agindo como se")
 newline()
    gameText("fossem os bonzinhos!")
 newpage()
    gameText("Mrrrrgh!")
 endstring()


script_history_0048:
    gameText("Você é incrível...")
 newline()
    gameText("Surpreendente!")
 newline()
    gameText("Você parece ser um")
 newline()
    gameText("verdadeiro idiota,")
 newpage()
    gameText("mas...")
 newline()
    gameText("Você é genial!")
 newline()
    gameText("Você pode ver")
 newline()
    gameText("perfeitamente todos")
 newpage()
    gameText("os movimentos dos")
 newline()
    gameText("seus oponentes.")
 newpage()


 newline()
    gameText("Você vê os meus")
 newline()
    gameText("completamente")
 newline()
    gameText("também, mas como?!")
 endstring()


script_history_0049:
 newline()
    gameText("Satan foi capaz de")
 newline()
    gameText("persuadir Majin Boo à")
 newline()
    gameText("acalmar-se por um curto")
 newline()
    gameText("período de tempo.")
 newline()
 paragraph()
 newline()
    gameText("Mas o espírito de vilão")
 newline()
    gameText("dentro dele já havia")
 newline()
    gameText("se transformado em")
 newline()
    gameText("Super Boo.")
 newpage()


    gameText("Piccolo, Gohan, e")
 newline()
    gameText("Gotenks foram absorvidos")
 newline()
    gameText("por Boo e ele ganhou")
 newline()
    gameText("mais poder ainda.")
 newline()
 newline()
 paragraph()
    gameText("Goku foi absorvido para")
 newline()
    gameText("dentro do corpo de Super")
 newline()
    gameText("Boo propositalmente")
 newline()
    gameText("afim de salvar Gohan")
 newline()
    gameText("e os outros, mas...")
 newline()
 endstring()


script_history_0050:
    gameText("Por conta disso o mal")
 newline()
    gameText("dentro de Majin Boo foi")
 newline()
    gameText("expelido, surgindo um Boo")
 newline()
    gameText("completamente malígno.")
 endstring()


script_history_0051:
 newline()
    gameText("Após Boo ser eliminado")
 newline()
    gameText("da Terra, ele chegou ao")
 newline()
    gameText("reino dos Kaiooshin.")
 newline()
    gameText("Colocando toda à")
 newline()
 paragraph()
    gameText("existência cósmica em")
 newline()
    gameText("perigo, Goku iniciava a")
 newline()
    gameText("batalha final e decisiva.")
 endstring()


script_history_0052:
    gameText("Muito bem!")
 newline()
    gameText("Vou ter que usar")
 newline()
    gameText("todo meu poder para")
 newline()
    gameText("vencer você!")
 newline()
 newpage()


 newline()
    gameText("Se formos derrotados")
 newline()
    gameText("aqui, todo universo")
 newline()
    gameText("será destruído...")
 endstring()


script_history_0053:
 newline()
    gameText("Hooooh!")
 newline()
    gameText("Uhoh uhoh!")
 newline()
    gameText(""Uhohoahohohoh!")
 endstring()


script_history_0054:
    gameText("...Maldição...")
 newline()
    gameText("Sempre a mesma")
 newline()
    gameText("coisa, independente")
 newline()
    gameText("do que eu faça...")
 newpage()


 newline()
    gameText("Esse cara parece")
 newline()
    gameText("que nunca fica")
 newline()
    gameText("cansado...")
 endstring()


script_history_0055:
    gameText("Goku começou a reunir")
 newline()
    gameText("energia para destruir")
 newline()
    gameText("Boo completamente.")
 newline()
    gameText("No entanto, ele precisava")
 newline()
    gameText("de tempo para reunir o")
 newline()
 paragraph()
    gameText("suficiente. Para dar o")
 newline()
    gameText("tempo que Goku precisava,")
 newline()
    gameText("Vegeta arriscou sua")
 newline()
    gameText("própria vida em batalha.")
 endstring()


script_history_0056:
    gameText("Certo! O que você acha")
 newline()
    gameText("disso, verme-maldito?!")
 endstring()


script_history_0057:
    gameText("Gih!")
 endstring()


script_history_0058:
    gameText("Kakarotto...")
 newline()
    gameText("V-Você estava...")
 newline()
    gameText("realmente lutando...")
 newline()
    gameText("com esse imbecil!?")
 endstring()


script_history_0059:
    gameText("No momento em que")
 newline()
    gameText("aparentemente Vegeta")
 newline()
    gameText("seria morto, Mr. Satan")
 newline()
    gameText("valentemente desafiou")
 newline()
    gameText("Boo.")
 newline()
 paragraph()
    gameText("Sem saber o motivo,")
 newline()
    gameText("depois de ouvir a voz")
 newline()
    gameText("de Satan, Boo viu-se")
 newline()
    gameText("angustiado e sentiu-se")
 newline()
    gameText("incapaz de atacar.")
 newpage()


 newline()
    gameText("Boo decidiu expelir")
 newline()
    gameText("aquela parte de si mesmo")
 newline()
    gameText("e então atacaou Satan,")
 newline()
    gameText("mais uma vez.")
 newline()
 paragraph()
    gameText("Porém, a parte expelida")
 newline()
    gameText("de Boo entrou na frente")
 newline()
    gameText("para proteger Satan.")
 newline()
 endstring()


script_history_0060:
    gameText("Eu odeio você!")
 newline()
    gameText("Deixe o Satan em paz!")
 endstring()


script_history_0061:
    gameText("Kakkakaka...")
 newline()
    gameText("Hoohohohoh!")
 endstring()


script_history_0062:
    gameText("...Caramba...")
 newline()
    gameText("Eu não posso vencer!")
 endstring()


script_history_0063:
 newline()
 newline()
    gameText("Enqaunto Majin Boo")
 newline()
    gameText("batalhava, Vegeta teve")
 newline()
    gameText("a ideia de restaurar")
 newline()
 paragraph()
    gameText("a Terra e todos os")
 newline()
    gameText("Terráqueos assassinados.")
 newpage()


    gameText("Vegeta, Majin Boo, e")
 newline()
    gameText("também Satan...")
 newline()
 newline()
    gameText("Após receber a ajuda")
 newline()
    gameText("deles, Goku estava")
 newline()
 paragraph()
    gameText("pronto para coletar")
 newline()
    gameText("o Ki de todos,")
 newline()
    gameText("transformando em uma")
 newline()
    gameText("Super Genki Dama.")
 endstring()


script_history_0064:
    gameText("Heh heh...")
 newline()
    gameText("Quanto mais perigoso")
 newline()
    gameText("isso parece...")
 newline()
    gameText("Mais eu fico animado!")
 endstring()


script_history_0065:
    gameText("Haaah!")
 endstring()


script_history_0066:
    gameText("Ufa...")
 newline()
    gameText("Finalmente...")
 newline()
    gameText("acabou...")
 endstring()


script_history_0067:
 newline()
 newline()
    gameText("Graças ao esforço de")
 newline()
    gameText("Goku e todos que")
 newline()
    gameText("ajudaram, Boo finalmente")
 newline()
 paragraph()
    gameText("foi destruído...")
 newline()
    gameText("Nenhuma célula de seu")
 newline()
    gameText("corpo restou.")
 newline()
 newpage()


    gameText("E o mundo novamente")
 newline()
    gameText("poderá ficar em paz.")
 newline()
    gameText("Goku e seus amigos")
 newline()
    gameText("retornaram para suas")
 newline()
    gameText("residências e famílias. ")
 newline()
 paragraph()
 newline()
    gameText("Sim, eles retornaram ")
 newline()
    gameText("para nosso Planeta Terra...")
 newline()
 endstring()


script_history_0068:
    gameText("Goten, Trunks.")
 newline()
    gameText("Me mostrem o poder")
 newline()
    gameText("que você dois")
 newline()
    gameText("adquiriram!")
 endstring()


script_history_0069:
    gameText("Tadaaah!")
 newline()
    gameText("Deus da Morte")
 newline()
    gameText("e da Justiça,")
 newline()
    gameText("Supeeer Gotenks!")
 endstring()


script_history_0070:
 newline()
    gameText("Isso é incrível,")
 newline()
    gameText("Gohan!")
 newline()
 newline()
 newpage()


    gameText("O velho Kaioshin")
 newline()
    gameText("realmente despertou")
 newline()
    gameText("seu poder adormecido,")
 newline()
    gameText("hein?")
 newpage()


    gameText("Diga, Gohan!")
 newline()
    gameText("Gostaria de lutar")
 newline()
    gameText("comigo!?")
 endstring()


script_history_0071:
    gameText("Clarou! Contra você,")
 newline()
    gameText("papai, Eu posso lutar")
 newline()
    gameText("demonstrando todo o")
 newline()
    gameText("meu poder!")
 endstring()


script_history_0072:
 newline()
    gameText("Recentemente, Papai")
 newline()
    gameText("e Vegeta fundiram-se")
 newline()
    gameText("em um único ser.")
 newpage()


 newline()
    gameText("Eu adoraria lutar")
 newline()
    gameText("contra esse guerreiro")
 newline()
    gameText("chamado Vegetto.")
 endstring()


script_history_0073:
    gameText("Vegeta e")
 newline()
    gameText("Kakarotto fundiram-se")
 newline()
    gameText("em um só...")
 newline()
 newpage()


    gameText("Suponho que agora eu")
 newline()
    gameText("seja Vegetto...")
 newline()
    gameText("Não, não apenas isso...")
 newline()
    gameText("Eu sou Super Vegetto!")
 endstring()


script_history_0074:
    gameText("Assim, a história de")
 newline()
    gameText("Goku, seus amigos e")
 newline()
    gameText("as Esféras do Dragão")
 newline()
    gameText("chegam ao fim.")
 newpage()


    gameText("No entanto, penso que")
 newline()
    gameText("Goku e seus amigos")
 newline()
    gameText("sempre terão novas")
 newline()
    gameText("histórias para começar")
 newline()
 newpage()


    gameText("em lugares distantes")
 newline()
    gameText("que nunca vimos.")
 newline()
 newline()
    gameText("Enquanto as Esféras")
 newline()
    gameText("do Dragão existirem...")
 endstring()


script_history_0075:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
    gameText("que Freeza resolveu")
 newline()
 paragraph()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0076:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
    gameText("que Freeza resolveu")
 newline()
 paragraph()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()


script_history_0077:
    gameText("Porém mesmo Goku")
 newline()
    gameText("com sua força renovada")
 newline()
    gameText("não era páreo para o")
 newline()
    gameText("poder colossal de Freeza.")
 newline()
 paragraph()
    gameText("Finalmente, Goku usou")
 newline()
    gameText("sua última carta na")
 newline()
    gameText("manga, a Genki Dama,")
 newline()
    gameText("contra Freeza.")
 newpage()


    gameText("Após um tempo de")
 newline()
    gameText("silêncio, todos viram")
 newline()
    gameText("que Freeza tinha sido")
 newline()
    gameText("derrotado. Foi então")
 newline()
    gameText("que Freeza resolveu")
 newline()
 paragraph()
    gameText("se vingar, nocauteando")
 newline()
    gameText("Piccolo e assassinando")
 newline()
    gameText("Kuririn.")
 endstring()