script_history_0000:
    gameText("Depois de uma luta muito ")
 newline()
    gameText("difícil, Goku e seus amigos")
 newline()
    gameText("salvaram a Terra, porém, ")
 newline()
    gameText("Yancha, Tenchi Han, Chaos ")
 newline()
    gameText("e até mesmo Piccolo foram ")
 newline()
 paragraph()
     gameText("mortos pelos Sayajins... ")
 newline()
 newline()
     gameText("Enquanto isso Buma e os ")
 newline()
    gameText("outros recolhiam os corpos ")
 newline()
    gameText("espalhados de seus amigos.")
 newpage()
    gameText("Kuririn relembra de uma ")
 newline()
    gameText("estranha conversa de Piccolo,")
 newline()
    gameText("informando que ele era um ")
 newline()
    gameText("Namekuseijin, e que Vegeta ")
 newline()
    gameText("havia ordado a Napa acabar")
newline()
    gameText("com todos, pois eles iriam")
newline()
   gameText("ao planeta Namekusei. Ele falou")
newline()
   gameText("que as eferas daquele planeta")
newline()
   gameText("são mais poderosas, do que")
newline()
   gameText("as das Terra.") 
 newline()
 paragraph()
 newline()
    gameText("However, Freeza had")
 newline()
    gameText("already arrived and")
 newline()
    gameText("had begun searching")
 newline()
    gameText("for the Dragon Balls.")
 newpage()
    gameText("Gohan and the others")
 newline()
    gameText("had managed to stall")
 newline()
    gameText("Freeza and Vegeta,")
 newline()
    gameText("and use the Dragon")
 newline()
    gameText("Balls to summon")
 newline()
 paragraph()
    gameText("Porunga. Then they")
 newline()
    gameText("wished for Piccolo")
 newline()
    gameText("to be warped to the")
 newline()
    gameText("planet Namek.")
 newpage()

 newline()
    gameText("After being warped")
 newline()
    gameText("to the planet, Piccolo")
 newline()
    gameText("fused with the")
 newline()
    gameText("Namekian named Nail")
 newline()
 paragraph()
    gameText("and obtained even")
 newline()
    gameText("greater power")
 newline()
    gameText("than before.")
 endstring()


script_history_0001:
    gameText("And so the battle")
 newline()
    gameText("begins between Piccolo")
 newline()
    gameText("and Freeza, now in his")
 newline()
    gameText("Ultimate Form.")
 endstring()


script_history_0002:
    gameText("Bastard! I'll make")
 newline()
    gameText("you feel the hatred")
 newline()
    gameText("of all the Namekians")
 newline()
    gameText("you've slain!")
 endstring()


script_history_0003:
    gameText("Before I kill you,")
 newline()
    gameText("allow me to show")
 newline()
    gameText("you my Ultimate")
 newline()
    gameText("Power.")
 newpage()


    gameText("It is said to")
 newline()
    gameText("be more fearsome")
 newline()
    gameText("than death")
 newline()
    gameText("itself.")
 endstring()


script_history_0004:
 newline()
    gameText("Kukkukku...")
 newline()
 newline()
 newline()
 newpage()


    gameText("I was careless")
 newline()
    gameText("back there...")
 newline()
    gameText("I completely")
 newline()
    gameText("underestimated you...")
 newpage()


 newline()
    gameText("You are far more")
 newline()
    gameText("capable than I had")
 newline()
    gameText("imagined...")
 newpage()


 newline()
    gameText("Allow me to show")
 newline()
    gameText("you MY power")
 newline()
    gameText("as well!")
 endstring()


script_history_0005:
 newline()
    gameText("D-Dammit...")
 newline()
 newline()
 newpage()


    gameText("After all the")
 newline()
    gameText("trouble they went")
 newline()
    gameText("through to get the")
 newline()
    gameText("Dragon Balls and")
 newpage()


    gameText("wish me back...")
 newpage()


    gameText("Sorry guys...")
 newline()
    gameText("looks like I won't")
 newline()
    gameText("be much help to")
 newline()
    gameText("you.")
 endstring()


script_history_0006:
    gameText("During the fight")
 newline()
    gameText("Piccolo and the Z")
 newline()
    gameText("Warriors seemed to")
 newline()
    gameText("be superior.")
 newline()
 newline()
 paragraph()
    gameText("However, Freeza's")
 newline()
    gameText("battle power")
 newline()
    gameText("seemed to come from")
 newline()
    gameText("another plane of")
 newline()
    gameText("existance. ")
 newpage()


    gameText("The Z Warriors")
 newline()
    gameText("could not even")
 newline()
    gameText("take another step.")
 newline()
 newline()
    gameText("Amidst the battle,")
 newline()
 paragraph()
    gameText("the silhouette of a")
 newline()
    gameText("fully-recovered Goku")
 newline()
    gameText("appeared in front of")
 newline()
    gameText("Piccolo and the others.")
 endstring()


script_history_0007:
    gameText("Though Piccolo had")
 newline()
    gameText("fused with Nail,")
 newline()
    gameText("he was helpless when")
 newline()
    gameText("faced with Freeza's")
 newline()
    gameText("Ultimate Form.")
 newline()
 paragraph()
    gameText("Amidst the battle,")
 newline()
    gameText("the silhouette of a")
 newline()
    gameText("fully-recovered Goku")
 newline()
    gameText("appeared in front of")
 newline()
    gameText("Piccolo and the others.")
 endstring()


script_history_0008:
 newline()
 newline()
    gameText("Special Battle 1")
 newline()
 newline()
    gameText("Son Gohan")
 newline()
 paragraph()
    gameText("   V.S.")
 newline()
        gameText("Gotenks")
      endstring()


script_history_0009:
 newline()
 newline()
    gameText("Special Battle 2")
 newline()
 newline()
    gameText("Son Goku")
 newline()
 paragraph()
    gameText("   V.S.")
 newline()
        gameText("Son Gohan")
      endstring()


script_history_0010:
 newline()
 newline()
    gameText("Special Battle 2")
 newline()
 newline()
    gameText("Son Goku")
 newline()
 paragraph()
    gameText("   V.S.")
 newline()
        gameText("Son Gohan")
      endstring()


script_history_0011:
 newline()
 newline()
    gameText("Final Battle")
 newline()
 newline()
    gameText("Son Gohan")
 newline()
 paragraph()
    gameText("   V.S.")
 newline()
        gameText("Vegetto")
      endstring()
     
     
     script_history_0012:
    gameText("     But even the newly-")
 newline()
    gameText("restored Goku was")
 newline()
    gameText("no match for Freeza's")
 newline()
    gameText("overwhelming power.")
 newline()
 newline()
 paragraph()
    gameText("Finally, Goku threw his")
 newline()
    gameText("trump card -- the")
 newline()
    gameText("Genki Dama -- at")
 newline()
    gameText("Freeza.")
 newpage()


 newline()
    gameText("After the silence")
 newline()
    gameText("cleared, everyone")
 newline()
    gameText("thought Freeza was")
 newline()
    gameText("defeated. It was then")
 newline()
 paragraph()
    gameText("that Freeza took his")
 newline()
    gameText("revenge, knocking")
 newline()
    gameText("Piccolo unconscious")
 newline()
    gameText("and killing Krillin.")
 endstring()


script_history_0013:
    gameText("But even the newly-")
 newline()
    gameText("restored Goku was")
 newline()
    gameText("no match for Freeza's")
 newline()
    gameText("overwhelming power.")
 newline()
 newline()
 paragraph()
    gameText("Finally, Goku threw his")
 newline()
    gameText("trump card -- the")
 newline()
    gameText("Genki Dama -- at")
 newline()
    gameText("Freeza.")
 newpage()


 newline()
    gameText("After the silence")
 newline()
    gameText("cleared, everyone")
 newline()
    gameText("thought Freeza was")
 newline()
    gameText("defeated. It was then")
 newline()
 paragraph()
    gameText("that Freeza took his")
 newline()
    gameText("revenge, knocking")
 newline()
    gameText("Piccolo unconscious")
 newline()
    gameText("and killing Krillin.")
 endstring()


script_history_0014:
    gameText("After the silence")
 newline()
    gameText("cleared, everyone")
 newline()
    gameText("thought Freeza was")
 newline()
    gameText("defeated. It was then")
 newline()
    gameText("that Freeza took his")
 newline()
 paragraph()
    gameText("revenge, knocking")
 newline()
    gameText("Piccolo unconscious")
 newline()
    gameText("and killing Krillin.")
 endstring()


script_history_0015:
    gameText("Goku became enraged")
 newline()
    gameText("after Krillin was killed.")
 newline()
    gameText("The Legendary Super")
 newline()
    gameText("Saiyan in him awoke.")
 endstring()


script_history_0016:
    gameText("I'm a Saiyan who")
 newline()
    gameText("was raised on")
 newline()
    gameText("Earth! For the")
 newline()
    gameText("sake of all the")
 newline()
    gameText("Saiyans and ")
 newpage()


    gameText("Namekians you've")
 newline()
    gameText("killed, I will")
 newline()
    gameText("destroy you!")
 endstring()


script_history_0017:
    gameText("What utter")
 newline()
    gameText("nonsense...")
 endstring()


script_history_0018:
 newline()
    gameText(".........")
 endstring()


script_history_0019:
 newline()
 newline()
    gameText("Goku defeated Freeza.")
 newline()
    gameText("The Z Warriors who had")
 newline()
    gameText("died were brought back")
 newline()
 paragraph()
    gameText("to life by Porunga, and")
 newline()
    gameText("Goku continued to train")
 newline()
    gameText("further in outer space.")
 newline()
 newpage()


    gameText("One year later, Freeza")
 newline()
    gameText("had been fully")
 newline()
    gameText("transformed into")
 newline()
    gameText("a cyborg, and showed")
 newline()
    gameText("up on Earth.")
 newline()
 paragraph()
 newline()
    gameText("However, Freeza was")
 newline()
    gameText("quickly dispatched by")
 newline()
    gameText("a lone Saiyan armed")
 newline()
    gameText("with a sword.")
 newpage()


    gameText("This Saiyan was a")
 newline()
    gameText("youth known as Trunks.")
 newline()
 newline()
    gameText("Trunks had come from")
 newline()
    gameText("a disasterous future")
 newline()
 paragraph()
    gameText("where murderous")
 newline()
    gameText("machines known as")
 newline()
    gameText("((QUOleft)Androids(QUOright) had")
 newline()
    gameText("appeared and caused")
 newline()
    gameText("death and destruction.")
 newline()
 newpage()


    gameText("Trunks' arrival had")
 newline()
    gameText("surely changed the")
 newline()
    gameText("future.")
 newline()
 newline()
    gameText("This was evident by")
 newline()
 paragraph()
    gameText("the arrival of Cell --")
 newline()
    gameText("an android whose")
 newline()
    gameText("strength far surpassed")
 newline()
    gameText("even the imagination")
 newline()
    gameText("of Trunks.")
 endstring()


script_history_0020:
    gameText("Cell absorbed many")
 newline()
    gameText("humans and Numbers 17")
 newline()
    gameText("and 18. Cell gained")
 newline()
    gameText("his Perfect Form.")
 endstring()


script_history_0021:
 newline()
    gameText("However, after his")
 newline()
    gameText("body became Perfect,")
 newline()
    gameText("Cell found himself")
 newline()
    gameText("confronted by a")
 newline()
 paragraph()
    gameText("warrior who was not")
 newline()
    gameText("yet scheduled to")
 newline()
    gameText("make his debut.")
 newline()
 newpage()


 newline()
 newline()
    gameText("It was Vegeta, who")
 newline()
    gameText("through intensive")
 newline()
    gameText("training had gained")
 newline()
 paragraph()
    gameText("power beyond that")
 newline()
    gameText("of a Super Saiyan.")
 endstring()


script_history_0022:
    gameText("You enjoy")
 newline()
    gameText("tormenting low-lifes")
 newline()
    gameText("like these guys,")
 newline()
    gameText("do ya?")
 newpage()


    gameText("Seems you thought")
 newline()
    gameText("that once in your")
 newline()
    gameText("((QUOleft)Perfect Form(QUOright),")
 newline()
    gameText("nothing could")
 newpage()


    gameText("stand in your")
 newline()
    gameText("way, huh?")
 endstring()


script_history_0023:
 newline()
    gameText("You're a pain in")
 newline()
    gameText("the ass...")
 newline()
 newline()
 newpage()


 newline()
    gameText("Well, at least you")
 newline()
    gameText("can help me warm")
 newline()
    gameText("up a bit, eh?")
 endstring()


script_history_0024:
    gameText("T-This can't be!")
 newline()
    gameText("I-...Im-...Impossible!")
 newline()
    gameText("My Perfect Body")
 newline()
    gameText("has...")
 newpage()


 newline()
    gameText("God dammiiiiiit!")
 newline()
 newline()
 newpage()


 newline()
    gameText("Just kidding!")
 endstring()


script_history_0025:
    gameText("Hehehe...")
 newline()
    gameText("You're stubborn, huh?")
 newline()
    gameText("It seems you're still")
 newline()
    gameText("barely alive...")
 endstring()


script_history_0026:
    gameText("Even with power")
 newline()
    gameText("beyond that of a")
 newline()
    gameText("Super Saiyan, Vegeta's")
 newline()
    gameText("attacks could not even")
 newline()
    gameText("come close to Cell's")
 newline()
 paragraph()
    gameText("power.")
 newline()
 newline()
    gameText("In anticipation of")
 newline()
    gameText("the other warriors'")
 newline()
    gameText("growth in power, Cell")
 newpage()


    gameText("informed them of the")
 newline()
    gameText("Cell Games which")
 newline()
    gameText("would be held in")
 newline()
    gameText("ten days' time.")
 newline()
 newline()
 paragraph()
    gameText("Cell also did this to")
 newline()
    gameText("strike terror into the")
 newline()
    gameText("hearts of all humanity,")
 newline()
    gameText("just to see the fear")
 newline()
    gameText("in their eyes.")
 newpage()


    gameText("Goku and the")
 newline()
    gameText("Z Warriors strategized")
 newline()
    gameText("and trained intensively")
 newline()
    gameText("in preparation for")
 newline()
    gameText("the fight with Cell.")
 newline()
 paragraph()
 newline()
    gameText("And then, the fated")
 newline()
    gameText("day came.")
 endstring()


script_history_0027:
    gameText("Even with power")
 newline()
    gameText("beyond that of a")
 newline()
    gameText("Super Saiyan, Vegeta's")
 newline()
    gameText("attacks could not even")
 newline()
    gameText("come close to Cell's")
 newline()
 paragraph()
    gameText("power.")
 newline()
 newline()
    gameText("In anticipation of")
 newline()
    gameText("the other warriors'")
 newline()
    gameText("growth in power, Cell")
 newpage()


    gameText("informed them of the")
 newline()
    gameText("Cell Games which")
 newline()
    gameText("would be held in")
 newline()
    gameText("ten day's time.")
 newline()
 newline()
 paragraph()
    gameText("Cell also did this to")
 newline()
    gameText("strike terror in the")
 newline()
    gameText("hearts of all humanity,")
 newline()
    gameText("just to see the fear")
 newline()
    gameText("in their eyes.")
 newpage()


    gameText("Goku and the")
 newline()
    gameText("Z Warriors strategized")
 newline()
    gameText("and trained intensively")
 newline()
    gameText("in preparation of")
 newline()
    gameText("the fight with Cell.")
 newline()
 paragraph()
 newline()
    gameText("And then, the fated")
 newline()
    gameText("day came.")
 endstring()


script_history_0028:
    gameText("Very well!")
 newline()
    gameText("Let's get our")
 newline()
    gameText("battle started,")
 newline()
    gameText("shall we?!")
 endstring()


script_history_0029:
 newline()
    gameText("So we're starting")
 newline()
    gameText("with you, huh...?")
 newline()
 newpage()


    gameText("While I must admit")
 newline()
    gameText("I looked forward to")
 newline()
    gameText("you the most,")
 newline()
    gameText("I wanted to save")
 newpage()


    gameText("you for last...")
 endstring()


script_history_0030:
 newline()
    gameText("I give up! You win!")
 newline()
    gameText("Now I know just")
 newline()
    gameText("how strong you are!")
 newpage()


 newline()
    gameText("I'm already spent.")
 endstring()


script_history_0031:
    gameText("Goku had already")
 newline()
    gameText("given in and Gohan")
 newline()
    gameText("was to be the next")
 newline()
    gameText("challenger.")
 newline()
 newline()
 paragraph()
    gameText("However, Cell was no")
 newline()
    gameText("match for Gohan")
 newline()
    gameText("after he unleashed")
 newline()
    gameText("his true power.")
 endstring()


script_history_0032:
    gameText("Cell tried to self-")
 newline()
    gameText("destruct but Goku gave")
 newline()
    gameText("his own life to save")
 newline()
    gameText("his friends.")
 newline()
 newline()
 paragraph()
    gameText("While everyone mourned")
 newline()
    gameText("the loss of Goku, Cell")
 newline()
    gameText("was revived in his")
 newline()
    gameText("Perfect Form!")
 newpage()


    gameText("However, Cell soon")
 newline()
    gameText("met with Gohan's")
 newline()
    gameText("Final Kamehameha.")
 newline()
 newline()
    gameText("One of Gohan's arms")
 newline()
 paragraph()
    gameText("had been injured, but")
 newline()
    gameText("with Goku's power")
 newline()
    gameText("supplementing his own,")
 newline()
    gameText("Gohan managed to")
 newpage()


    gameText("unleash his ki one")
 newline()
    gameText("final time.")
 newline()
 newline()
    gameText("At last, the fight with")
 newline()
    gameText("Cell had come to")
 newline()
 paragraph()
    gameText("an end.")
 newline()
 newpage()


    gameText("Several years after")
 newline()
    gameText("the battle with Cell")
 newline()
    gameText("ended, a new World")
 newline()
    gameText("Martial Arts")
 newline()
    gameText("Tournament had")
 newline()
 paragraph()
    gameText("started and there")
 newline()
    gameText("was a meeting of")
 newline()
    gameText("old friends.")
 newpage()


    gameText("Meanwhile, an")
 newline()
    gameText("evil demon's henchmen")
 newline()
    gameText("were working behind")
 newline()
    gameText("the scenes to")
 newline()
    gameText("resurrect Majin Buu.")
 newline()
 paragraph()
 newline()
    gameText("Goku was only allowed")
 newline()
    gameText("to return to Earth")
 newline()
    gameText("for one day. ")
 newpage()


    gameText("However, to prevent")
 newline()
    gameText("Buu's resurrection he")
 newline()
    gameText("went with Vegeta and")
 newline()
    gameText("the others toward")
 newline()
    gameText("their new enemy's")
 newline()
 paragraph()
    gameText("hideout.")
 newline()
 newline()
 endstring()


script_history_0033:
    gameText("Cell tried to self-")
 newline()
    gameText("destruct but Goku gave")
 newline()
    gameText("his own life to save")
 newline()
    gameText("his friends.")
 newline()
 newline()
 paragraph()
    gameText("While everyone mourned")
 newline()
    gameText("the loss of Goku, Cell")
 newline()
    gameText("was revived in his")
 newline()
    gameText("Perfect Form!")
 newpage()


    gameText("However, Cell soon")
 newline()
    gameText("met with Gohan's")
 newline()
    gameText("Final Kamehameha.")
 newline()
 newline()
    gameText("One of Gohan's arms")
 newline()
 paragraph()
    gameText("had been injured, but")
 newline()
    gameText("with Goku's power")
 newline()
    gameText("supplementing his own,")
 newline()
    gameText("Gohan managed to")
 newpage()


    gameText("unleash his ki one")
 newline()
    gameText("final time.")
 newline()
 newline()
    gameText("At last, the fight with")
 newline()
    gameText("Cell had come to")
 newline()
 paragraph()
    gameText("an end.")
 newline()
 newpage()


 newline()
    gameText("Several years after")
 newline()
    gameText("the battle with Cell")
 newline()
    gameText("ended, a new World")
 newline()
    gameText("Martial Arts")
 newline()
 paragraph()
    gameText("Tournament had begun")
 newline()
    gameText("and there was a")
 newline()
    gameText("meeting of old friends.")
 newpage()


    gameText("Meanwhile, an evil")
 newline()
    gameText("demon's henchmen were")
 newline()
    gameText("working behind the")
 newline()
    gameText("scenes to resurrect")
 newline()
    gameText("Majin Buu.")
 newline()
 paragraph()
 newline()
    gameText("Goku was only allowed")
 newline()
    gameText("to return to Earth")
 newline()
    gameText("for one day. ")
 newpage()


 newline()
 newline()
    gameText("However, to prevent")
 newline()
    gameText("Buu's resurrection he")
 newline()
    gameText("went with Vegeta and")
 newline()
 paragraph()
    gameText("the others toward")
 newline()
    gameText("the hideout of their")
 newline()
    gameText("new enemy.")
 endstring()


script_history_0034:
    gameText("Vegeta was turned")
 newline()
    gameText("into a warrior of evil")
 newline()
    gameText("by Babidi. He then")
 newline()
    gameText("clashed with Goku.")
 endstring()


script_history_0035:
    gameText("Using my supreme")
 newline()
    gameText("power, I'll bring")
 newline()
    gameText("this to a quick end!")
 endstring()


script_history_0036:
 newline()
    gameText("Using my supreme")
 newline()
    gameText("power, I'll bring")
 newline()
    gameText("this to a quick end!")
 endstring()


script_history_0037:
    gameText("Let's go!")
 newline()
    gameText("I'm going to kill")
 newline()
    gameText("you, Kakarotto!")
 endstring()


script_history_0038:
    gameText("Goku and Vegeta's")
 newline()
    gameText("battle released energy")
 newline()
    gameText("unlike any before it!")
 newline()
    gameText("Majin Buu was revived.")
 endstring()


script_history_0039:
    gameText("We can set aside")
 newline()
    gameText("our match for now;")
 newline()
    gameText("your concentration is")
 newline()
    gameText("broken.")
 newline()
 newpage()


 newline()
    gameText("Seems your mind is")
 newline()
    gameText("set on Majin Buu.")
 endstring()


script_history_0040:
    gameText("Since it's my damned")
 newline()
    gameText("fault he's here, I'll")
 newline()
    gameText("go take care of")
 newline()
    gameText("Majin Buu.")
 newline()
 newpage()


    gameText("The conclusion of our")
 newline()
    gameText("battle will have to")
 newline()
    gameText("wait until I'm done")
 newline()
    gameText("with that.")
 newpage()


    gameText("Provided I live")
 newline()
    gameText("through this...")
 endstring()


script_history_0041:
 newline()
 newline()
    gameText("Unable to deny the")
 newline()
    gameText("feelings he had for")
 newline()
    gameText("his family, Vegeta")
 newline()
 paragraph()
    gameText("stood alone against")
 newline()
    gameText("Majin Buu.")
 newline()
 newpage()


 newline()
 newline()
    gameText("Because this was the")
 newline()
    gameText("first time Vegeta")
 newline()
    gameText("fought for the sake")
 newline()
 paragraph()
    gameText("of someone other than")
 newline()
    gameText("himself, he fought with")
 newline()
    gameText("a new determination.")
 newline()
 endstring()


script_history_0042:
    gameText("This ugly imbecile")
 newline()
    gameText("is Majin Buu?")
 newline()
    gameText("I'm not going to")
 newline()
    gameText("hell by myself!")
 newpage()


 newline()
    gameText("I'm gonna take you")
 newline()
    gameText("with me, asshole!")
 endstring()


script_history_0043:
 newline()
    gameText("You made me mad!")
 newline()
    gameText("Mrrrrgh!")
 newline()
    gameText("I'll kill yooou!")
 endstring()


script_history_0044:
    gameText("I'll defeat you: I'll")
 newline()
    gameText("make you explode")
 newline()
    gameText("into pieces so small")
 newline()
    gameText("you won't be able")
 newline()
 newpage()


    gameText("to regenerate again!")
 newpage()


 newline()
    gameText("This is farewell...")
 newline()
    gameText("Bulma...")
 newline()
    gameText("Trunks...")
 newline()
 newpage()


 newline()
    gameText("And you too,")
 newline()
    gameText("Kakarotto...")
 endstring()


script_history_0045:
 newline()
    gameText("Vegeta gave his life")
 newline()
    gameText("to destroy Majin Buu.")
 newline()
    gameText("However, the attack")
 newline()
    gameText("Vegeta bet his life on")
 newline()
 paragraph()
    gameText("was not enough. Majin")
 newline()
    gameText("Buu was easily able to")
 newline()
    gameText("restore himself.")
 newline()
 newpage()


 newline()
    gameText("In order to keep the")
 newline()
    gameText("Western Capital from")
 newline()
    gameText("being destroyed, Goku")
 newline()
    gameText("faced off against")
 newline()
 paragraph()
    gameText("Majin Buu and his")
 newline()
    gameText("unfathomable hidden")
 newline()
    gameText("power.")
 endstring()


script_history_0046:
 newline()
    gameText("Man, Vegeta and I")
 newline()
    gameText("didn't take you")
 newline()
    gameText("seriously enough!")
 newline()
 newline()
 newpage()


    gameText("Until now, I'd")
 newline()
    gameText("thought it impossible")
 newline()
    gameText("for Majin Buu to be")
 newline()
    gameText("this friggin' strong.")
 endstring()


script_history_0047:
    gameText("I'm gonna kill you!")
 newline()
    gameText("I hate guys like you,")
 newline()
    gameText("acting like you're so")
 newline()
    gameText("great! Mrrrrgh!")
 endstring()


script_history_0048:
    gameText("You're incredible...")
 newline()
    gameText("What a surprise!")
 newline()
    gameText("You look like a")
 newline()
    gameText("real moron, but...")
 newpage()


    gameText("You're a genius!")
 newline()
    gameText("You can see right")
 newline()
    gameText("through all your")
 newline()
    gameText("opponents' moves.")
 newpage()


 newline()
    gameText("You'll see completely")
 newline()
    gameText("through mine too,")
 newline()
    gameText("but how?!")
 endstring()


script_history_0049:
 newline()
    gameText("Satan was able to")
 newline()
    gameText("pursuade Majin Buu into")
 newline()
    gameText("becoming calm for a")
 newline()
    gameText("short period of time.")
 newline()
 paragraph()
 newline()
    gameText("But the villain's spirit")
 newline()
    gameText("within him transformed")
 newline()
    gameText("into Super Buu.")
 newpage()


    gameText("Piccolo, Gohan, and")
 newline()
    gameText("Gotenks were absorbed")
 newline()
    gameText("into Buu and he gained")
 newline()
    gameText("even more power.")
 newline()
 newline()
 paragraph()
    gameText("Goku was absorbed")
 newline()
    gameText("into Super Buu's body")
 newline()
    gameText("as well and managed")
 newline()
    gameText("to save Gohan and")
 newline()
    gameText("the others, but...")
 newline()
 endstring()


script_history_0050:
    gameText("Because the former")
 newline()
    gameText("Majin Buu was also")
 newline()
    gameText("expelled, a new, pure-")
 newline()
    gameText("evil Buu was born.")
 endstring()


script_history_0051:
 newline()
    gameText("After Buu wiped out")
 newline()
    gameText("the Earth, he arrived")
 newline()
    gameText("at the Kaioshin realm.")
 newline()
    gameText("And with the entirety")
 newline()
 paragraph()
    gameText("of the cosmos on the")
 newline()
    gameText("line, Goku began the")
 newline()
    gameText("final decisive battle.")
 endstring()


script_history_0052:
    gameText("Alright!")
 newline()
    gameText("I'll hafta use full")
 newline()
    gameText("power from the")
 newline()
    gameText("get go!")
 newline()
 newpage()


 newline()
    gameText("If we're defeated,")
 newline()
    gameText("the whole universe")
 newline()
    gameText("will be destroyed...")
 endstring()


script_history_0053:
 newline()
    gameText("Hooooh!")
 newline()
    gameText("Uhoh uhoh!")
 newline()
    gameText("Whoahohohoh!")
 endstring()


script_history_0054:
    gameText("...God dammit...")
 newline()
    gameText("It's always the")
 newline()
    gameText("same, regardless of")
 newline()
    gameText("what I do...")
 newpage()


 newline()
    gameText("That guy just")
 newline()
    gameText("doesn't get")
 newline()
    gameText("tired at all...")
 endstring()


script_history_0055:
    gameText("Goku began to gather")
 newline()
    gameText("energy to destroy")
 newline()
    gameText("Buu completely.")
 newline()
    gameText("However, it would take")
 newline()
    gameText("quite some time to")
 newline()
 paragraph()
    gameText("complete. In order to")
 newline()
    gameText("give Goku the time he")
 newline()
    gameText("needed, Vegeta risked")
 newline()
    gameText("his life in battle.")
 endstring()


script_history_0056:
    gameText("Alright! You want")
 newline()
    gameText("some, asshole?!")
 endstring()


script_history_0057:
    gameText("Gih!")
 endstring()


script_history_0058:
    gameText("Kakarotto...")
 newline()
    gameText("Y-You were...")
 newline()
    gameText("actually fighting...")
 newline()
    gameText("this jerk!?")
 endstring()


script_history_0059:
    gameText("Right at the moment")
 newline()
    gameText("it seemed Vegeta")
 newline()
    gameText("would be killed, Mr.")
 newline()
    gameText("Satan valiantly stood")
 newline()
    gameText("against Buu. Without")
 newline()
 paragraph()
    gameText("knowing why, after")
 newline()
    gameText("listening to Satan's")
 newline()
    gameText("voice, Buu let go of")
 newline()
    gameText("his anguish, and was")
 newline()
    gameText("unable to attack.")
 newpage()


 newline()
    gameText("Buu decided to purge")
 newline()
    gameText("that part of himself")
 newline()
    gameText("from within, and then")
 newline()
    gameText("attacked Satan once")
 newline()
 paragraph()
    gameText("more. However, the")
 newline()
    gameText("new Buu struck back")
 newline()
    gameText("in order to protect")
 newline()
    gameText("Satan.")
 endstring()


script_history_0060:
    gameText("I hate you!")
 newline()
    gameText("Leave Satan alone!")
 endstring()


script_history_0061:
    gameText("Kakkakaka...")
 newline()
    gameText("Hoohohohoh!")
 endstring()


script_history_0062:
    gameText("...Oh, man...")
 newline()
    gameText("I can't win.")
 endstring()


script_history_0063:
 newline()
 newline()
    gameText("While Majin Buu was")
 newline()
    gameText("in battle, Vegeta got")
 newline()
    gameText("the idea to restore")
 newline()
 paragraph()
    gameText("the Earth and all of")
 newline()
    gameText("the slain Earthlings.")
 newpage()


    gameText("Vegeta, Majin Buu, and")
 newline()
    gameText("then Satan...")
 newline()
 newline()
    gameText("After receiving their")
 newline()
    gameText("assistance, Goku was")
 newline()
 paragraph()
    gameText("able to collect")
 newline()
    gameText("everyone's Ki and form")
 newline()
    gameText("it into a Super")
 newline()
    gameText("Genki Dama.")
 endstring()


script_history_0064:
    gameText("Heh heh...")
 newline()
    gameText("When it gets")
 newline()
    gameText("dangerous like this,")
 newline()
    gameText("I get really excited!")
 endstring()


script_history_0065:
    gameText("Haaah!")
 endstring()


script_history_0066:
    gameText("Whew...")
 newline()
    gameText("It's...")
 newline()
    gameText("over...")
 endstring()


script_history_0067:
 newline()
 newline()
    gameText("Finally, thanks to the")
 newline()
    gameText("actions of Goku and")
 newline()
    gameText("the others, Buu was")
 newline()
 paragraph()
    gameText("destroyed; not one")
 newline()
    gameText("living cell from his")
 newline()
    gameText("body was left.")
 newline()
 newpage()


    gameText("And the world again")
 newline()
    gameText("became peaceful. Goku")
 newline()
    gameText("and friends returned")
 newline()
    gameText("to the places they")
 newline()
    gameText("came from. ")
 newline()
 paragraph()
 newline()
    gameText("Yes, they headed ")
 newline()
    gameText("toward our Earth...")
 newline()
 endstring()


script_history_0068:
    gameText("Goten, Trunks. Show")
 newline()
    gameText("your big brother the")
 newline()
    gameText("power that you two")
 newline()
    gameText("have!")
 endstring()


script_history_0069:
    gameText("Tadaaah!")
 newline()
    gameText("God of Death")
 newline()
    gameText("and Justice,")
 newline()
    gameText("Supeeer Gotenks!")
 endstring()


script_history_0070:
 newline()
    gameText("That's amazing,")
 newline()
    gameText("Gohan!")
 newline()
 newline()
 newpage()


    gameText("That old Kaioshin")
 newline()
    gameText("really drew out")
 newline()
    gameText("your latent power,")
 newline()
    gameText("huh?")
 newpage()


    gameText("Say, Gohan!")
 newline()
    gameText("Wanna have a")
 newline()
    gameText("match with me!?")
 endstring()


script_history_0071:
    gameText("Alright! Against you,")
 newline()
    gameText("dad, I can fight")
 newline()
    gameText("without holding back!")
 endstring()


script_history_0072:
 newline()
    gameText("Recently, Dad and")
 newline()
    gameText("Vegeta fused")
 newline()
    gameText("together.")
 newpage()


 newline()
    gameText("I want to fight")
 newline()
    gameText("against this warrior")
 newline()
    gameText("they call ((QUOleft)Vegetto(QUOright).")
 endstring()


script_history_0073:
    gameText("Vegeta and")
 newline()
    gameText("Kakarotto have")
 newline()
    gameText("fused together...")
 newline()
 newpage()


    gameText("I suppose I'm")
 newline()
    gameText("Vegetto now...")
 newline()
    gameText("No, not just that...")
 newline()
    gameText("I'm Super Vegetto!")
 endstring()


script_history_0074:
    gameText("Thus, the story of")
 newline()
    gameText("Goku, his friends and")
 newline()
    gameText("the Dragon Balls")
 newline()
    gameText("comes to a close.")
 newpage()


    gameText("However, I think that")
 newline()
    gameText("Goku and his friends")
 newline()
    gameText("will always have new")
 newline()
    gameText("stories starting up")
 newline()
 newpage()


    gameText("in faraway lands we")
 newline()
    gameText("have never seen.")
 newline()
 newline()
    gameText("For as long as the")
 newline()
    gameText("Dragon Balls exist...")
 endstring()


script_history_0075:
    gameText("But, even the")
 newline()
    gameText("newly-restored")
 newline()
    gameText("Goku was not")
 newline()
    gameText("match for Freeza's")
 newline()
    gameText("overwhelming power.")
 newline()
 paragraph()
    gameText("Finally, Goku threw his")
 newline()
    gameText("trump card -- the")
 newline()
    gameText(" Genki Dama -- at")
 newline()
    gameText("Freeza.")
 newpage()


    gameText("After the silence")
 newline()
    gameText("cleared, everyone")
 newline()
    gameText("thought Freeza was")
 newline()
    gameText("defeated. It was then")
 newline()
    gameText("that Freeza took his")
 newline()
 paragraph()
    gameText("revenge, knocking")
 newline()
    gameText("Piccolo unconscious")
 newline()
    gameText("and killing Krillin.")
 endstring()


script_history_0076:
    gameText("But, even the")
 newline()
    gameText("newly-restored")
 newline()
    gameText("Goku was no")
 newline()
    gameText("match for Freeza's")
 newline()
    gameText("overwhelming power.")
 newline()
 paragraph()
    gameText("Finally, Goku threw his")
 newline()
    gameText("trump card -- the")
 newline()
    gameText(" Genki Dama -- at")
 newline()
    gameText("Freeza.")
 newpage()


    gameText("After the silence")
 newline()
    gameText("cleared, everyone")
 newline()
    gameText("thought Freeza was")
 newline()
    gameText("defeated. It was then")
 newline()
    gameText("that Freeza took his")
 newline()
 paragraph()
    gameText("revenge, knocking")
 newline()
    gameText("Piccolo unconscious")
 newline()
    gameText("and killing Krillin.")
 endstring()


script_history_0077:
    gameText("But, even the")
 newline()
    gameText("newly-restored")
 newline()
    gameText("Goku was no")
 newline()
    gameText("match for Freeza's")
 newline()
    gameText("overwhelming power.")
 newline()
 paragraph()
    gameText("Finally, Goku threw his")
 newline()
    gameText("trump card -- the")
 newline()
    gameText(" Genki Dama -- at")
 newline()
    gameText("Freeza.")
 newpage()


    gameText("After the silence")
 newline()
    gameText("cleared, everyone")
 newline()
    gameText("thought Freeza was")
 newline()
    gameText("defeated. It was then")
 newline()
    gameText("that Freeza took his")
 newline()
 paragraph()
    gameText("revenge, knocking")
 newline()
    gameText("Piccolo unconscious")
 newline()
    gameText("and killing Krillin.")
 endstring()
