
credits_0000: 
 startOne()
      gameText("Staff")
 endstring()

 
credits_0001:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 startOne()
      gameText("Executive Producer")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Kazumasa Ogata")
 endstring()

 
credits_0002:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 startOne()
      gameText("Producers")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Takeo Isogai")
 newline()
 startOne()
      gameText("Toshihiro Suzuki")
 endstring()

 
credits_0003:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 startOne()
      gameText("Coordinators")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("De Yasu")
 newline()
 startOne()
      gameText("Kabao Isojin")
 endstring()

 
credits_0004:
 newline()
 newline()
 newline()
 newline()
 startOne()
      gameText("Programmers")
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Happy Hasei")
 newline()
 startOne()
      gameText("CLQ")
 newline()
 startOne()
      gameText("MNT(4E)KWI 1996")
 newline()
 startOne()
      gameText("Maruko")
 newline()
 newpage()
 startOne()
      gameText("Mitsu")
 endstring()

 
credits_0005:
 newline()
 newline()
 newline()
 newline()
 startOne()
      gameText("Designers")
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("TAKO2")
 newline()
 startOne()
      gameText("Paul Paula")
 newline()
 startOne()
      gameText("Laru Itagawa")
 newline()
 startOne()
      gameText("Waya")
 endstring()


 credits_0006:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 startTwo()
      gameText("H")
 startOne()
      gameText("Torosuke")
 newline()
 newline()
 startOne()
      gameText("Ichi Fuji")
 newline()
 startOne()
      gameText("Ni Taka")
 newline()
 startOne()
      gameText("San Nasubi")
 endstring()

 
credits_0007:
 newline()
 newline()
 newline()
 newline()
 startOne()
      gameText("Composers")
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Takano")
 newline()
 startOne()
      gameText("Nakajima")
 newline()
 startOne()
      gameText("Tonkupon")
 newline()
 startOne()
      gameText("Chatrita")
 endstring()

 
credits_0008:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 startOne()
      gameText("Animators")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Ganchi")
 newline()
 startOne()
      gameText("Sarusaru")
 endstring()

 
credits_0009:
 newline()
 newline()
 newline()
 newline()
 startOne()
      gameText("Toei Animation")
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Kozo Morishita")
 newline()
 startOne()
      gameText("Seiichi Hiruta")
 newline()
 startOne()
      gameText("Hiroshi Takeda")
 endstring()

 
credits_0010:
 newline()
 newline()
 newline()
 newline()
 startOne()
      gameText("Character Voices")
 newline()
 newpage()
 newline()
 startTwo()
      gameText("D")
 startOne()
      gameText("Son Goku")
 newline()
 startOne()
      gameText("Son Gohan")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Masako Nozawa")
 endstring()

 
credits_0011:
 newline()
 newline()
 newline()
 startTwo()
      gameText("D")
 startOne()
      gameText("Piccolo")
 newline()
 newline()
 newpage()
 startTwo()
      gameText("H")
 startOne()
      gameText("Toshio Furukawa")
 newline()
 newline()
 startTwo()
      gameText("D")
 startOne()
      gameText("Gotenks")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Masako Nozawa")
 newline()
 newpage()
 startOne()
      gameText("Takeshi Kusao")
 endstring()

 
credits_0012:
 newline()
 newline()
 newline()
 startTwo()
      gameText("D")
 startOne()
      gameText("Vegetto")
 newline()
 newline()
 newpage()
 startTwo()
      gameText("H")
 startOne()
      gameText("Masako Nozawa")
 newline()
 startOne()
      gameText("Ryo Horikawa")
 newline()
 newline()
 startTwo()
      gameText("D")
 startOne()
      gameText("Vegeta")
 newline()
 newline()
 newpage()
 startTwo()
      gameText("H")
 startOne()
      gameText("Ryo Horikawa")
 endstring()

 
credits_0013:
 newline()
 newline()
 newline()
 startTwo()
      gameText("D")
 startOne()
      gameText("Cell")
 newline()
 newline()
 newpage()
 startTwo()
      gameText("H")
 startOne()
      gameText("Norio Wakamoto")
 newline()
 newline()
 startTwo()
      gameText("D")
 startOne()
      gameText("Freeza")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Ryusei Nakao")
 endstring()

 
credits_0014:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 startTwo()
      gameText("D")
 startOne()
      gameText("Buu")
 newline()
 startOne()
      gameText("Mister Buu")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Kozo Shioya")
 endstring()

 
credits_0015:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 startOne()
      gameText("Assist Work")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Yasuomi Shimizu")
 newline()
 startOne()
      gameText("Daisuke Uchiyama")
 endstring()

 
credits_0016:
 newline()
 newline()
 newline()
 newline()
 startOne()
      gameText("Special Thanks")
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Takashi Shoji")
 newline()
 startOne()
      gameText("Hisashi Fujiwara")
 newline()
 startOne()
      gameText("Koji Hoshikawa")
 endstring()

 
credits_0017:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Hirotaka Watanabe")
 newline()
 startOne()
      gameText("Kumi Sato")
 newline()
 startOne()
      gameText("Hirofumi Inagaki")
 newline()
 startOne()
      gameText("Kenichiro Otsuka")
 endstring()

 
credits_0018:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Michito Okamoto")
 newline()
 startOne()
      gameText("Yumiko Kosaka")
 newline()
 startOne()
      gameText("Takahiro Mizuno")
 newline()
 startOne()
      gameText("Jun Kazumi")
 endstring()

 
credits_0019:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 startOne()
      gameText("Weekly Jump")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Nobuhiko Horie")
 newline()
 startOne()
      gameText("Toshimasa Takahashi")
 endstring()

 
credits_0020:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Fuyuto Takeda")
 newline()
 startOne()
      gameText("Hisanaga Otsuka")
 endstring()

 
credits_0021:
 newline()
 newline()
 newline()
 newline()
 startOne()
      gameText("Monthly V Jump")
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Kazuhiko Torishima")
 newline()
 startOne()
      gameText("Yuu Kondou")
 newline()
 startOne()
      gameText("Kenji Okamoto")
 endstring()

 
credits_0022:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Taizo Nakamura")
 newline()
 startOne()
      gameText("Muneharu Machida")
 endstring()

 
credits_0023:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Tsuneo Matsumoto")
 newline()
       startOne()
      gameText("Naoto Akamatsu")
 newline()
 startOne()
      gameText("Yoshitaka Kiyono")
 endstring()

 
credits_0024:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Makoto Iwahara")
 newline()
 startOne()
      gameText("Noriaki Suganuma")
 endstring()

 
credits_0025:
 newline()
 newline()
 newline()
 newline()
 startOne()
      gameText("Monthly V Jump")
 newline()
 newpage()
 startOne()
      gameText("Game Monitor")
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Tetsuya Maruoka")
 newline()
 startOne()
      gameText("Takeshi Okuyama")
 newline()
 startOne()
      gameText("Eri Murata")
 endstring()

 
credits_0026:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Takayuki Iwabuchi")
 newline()
 startOne()
      gameText("Yusuke Takei")
 newline()
 startOne()
      gameText("Yurie Kobayashi")
 newline()
 startOne()
      gameText("Yutaka Ito")
 endstring()

 
credits_0027:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Takae Asakura")
 newline()
 startOne()
      gameText("Minako Horiuchi")
 newline()
 startOne()
      gameText("Daisuke Iwasaki")
 newline()
 startOne()
      gameText("Yumi Abe")
 endstring()

 
credits_0028:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Akihisa Takahashi")
 newline()
 startOne()
      gameText("Kosuke Nishida")
 newline()
 startOne()
      gameText("Yuko Sawai")
 newline()
 startOne()
      gameText("Naoyuki Hosaka")
 endstring()

 
credits_0029:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Yusuke Fukuizumi")
 newline()
 startOne()
      gameText("Risa Kobayashi")
 newline()
 startOne()
      gameText("Miki Sakamoto")
 newline()
 startOne()
      gameText("Takamasa Honma")
 newline()
 newpage()
 startOne()
      gameText("Yoshiyuki Uchida")
 endstring()

 
credits_0030:
 newline()
 startOne()
      gameText("Twilight Translations")
 newline()
 newline()
 startOne()
      gameText("Programmer")
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("RedComet")
 newline()
 newpage()
 newline()
 startTwo()
 startOne()
      gameText("Translator(47)Editor")
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("DarknessSavior")
 newline()
 newline()
 startTwo()
      gameText(" ")
 startOne()
      gameText("Special Thanks")
 newline()
 newpage()
 startTwo()
      gameText("H")
 startOne()
      gameText("Tom")
 newline()
 startOne()
      gameText("Deuce")
 newline()
 startOne()
      gameText("Throughhim")
 newline()
 startOne()
      gameText("BRPXQZME")
 endstring()

 
credits_0031:
 newline()
 newline()
 newline()
 newline()
 newline()
 newpage()
 newline()
 newline()
 startTwo()
      gameText("H")
 startOne()
      gameText("Project DB")
 endstring()