vs_mode_configuration:
    gameText("           Handicap")
 newline()
    gameText("        ..........Ki..........    ")
 newline()
    gameText("      / ......Attack...... /")
 newline()
    gameText("      / .....Defense..... /")
 newline()
    gameText("COM LEVEL....................")
 newline()
    gameText("BGM......................")
 endstring()
 vsOptionOne()
 vsOptionTwo()
 vsOptionThree()
 vsOptionFour()
 vsOptionFive()
 vsOptionSix()
 endstring()
 endstring()