origin $001FE2B9
text_scene_01:
    text_cut_scene("À MEDIDA QUE AS JOIAS DO")
newline()
    text_cut_scene("INFINITO CAEM NA TERRA, A")
newline()
    text_cut_scene("RAÇA HUMANA COMEÇA A")
newline()
    text_cut_scene("PERCEBER QUE ESTÃO EM GRAVE")
newline()
    text_cut_scene("PERIGO.")
newline()
    text_cut_scene("OS HERÓIS, DETERMINADOS A")
newline()
    text_cut_scene("AJUDAR ADAM WARLOCK, PARTEM")
newline()
    text_cut_scene("EM BUSCA DAS JOIAS QUE FORAM")
newline()
    text_cut_scene("ESPALHADAS PELO MUNDO.")
newline()
    text_cut_scene("O SUPERCOMPUTADOR DA")
newline()
    text_cut_scene("EMPRESA STARK INDICOU QUATRO")
newline()
    text_cut_scene("LOCALIZAÇÕES ONDE QUE AS")
newline()
    text_cut_scene("JOIAS DO INFINITO PODERIAM")
newline()
    text_cut_scene("TER CAÍDO.")
paragraph()
    text_cut_scene("1. PRÓXIMO AO CASTELO DO")
newline()
    text_cut_scene("  DR. DESTINO NA LATVÉRIA.")
newline()
    text_cut_scene("2. NA BACIA DO RIO AMAZONAS,")
newline()
    text_cut_scene("  NA REGIÃO CENTRAL DA")
newline()
    text_cut_scene("  AMÉRICA DO SUL.")
newline()
    text_cut_scene("3. ALASCA, NA REGIÃO NORTE DA")
newline()
    text_cut_scene("  AMÉRICA DO NORTE.")
newline()
    text_cut_scene("4. NO AQUÁRIO DE BOSTON, NA")
newline()
    text_cut_scene("  REGIÃO LESTE DA")
newline()
    text_cut_scene("  AMÉRICA DO NORTE.")
paragraph()
    text_cut_scene(""INVESTIGUEM ESTAS ÁREAS"")
newline()
    text_cut_scene("" IMEDIATAMENTE!"")
endstring()
text_cut_scene_02:
    text_cut_scene("DEPOIS DE PEGAREM A SEGUNDA")
newline()
    text_cut_scene("JOIA, NOSSOS HERÓIS DESCOBREM")
newline()
    text_cut_scene("INFORMAÇÕES VALIOSAS.")
newline()
    text_cut_scene("O INIMIGO SE CHAMA MAGUS.")
newline()
    text_cut_scene("ELE ESTÁ REUNINDO AS JOIAS E")
newline()
    text_cut_scene("ESTA USANDO COMO BASE UMA")
newline()
    text_cut_scene("ENORME NAVE ESPACIAL QUE")
newline()
    text_cut_scene("ESTA EM ÓRBITA. O UNIVERSO")
newline()
    text_cut_scene("NUNCA ESTARÁ SEGURO ATÉ")
newline()
    text_cut_scene("O MAGUS SER DERROTADO.")
newline()
    text_cut_scene("COM ISSO EM MENTE, OS")
newline()
    text_cut_scene("HERÓIS DECIDIRAM ATACAR")
newline()
    text_cut_scene("A NAVE ESPACIAL.")
endstring()
text_cut_scene_03:
    text_cut_scene("OS HERÓIS FINALMENTE")
newline()
    text_cut_scene("DERROTARAM O MAGUS. MAS")
newline()
    text_cut_scene("ELE SÓ TINHA UMA JOIA.")
newline()
    text_cut_scene("NESSE MOMENTO, UMA MENSAGEM")
newline()
    text_cut_scene("APARECEU NA TELA DO")
newline()
    text_cut_scene("COMPUTADOR.")
newline()
    text_cut_scene(""EU SOU THANOS. OUÇAM HERÓIS"")
newline()
    text_cut_scene(" DA TERRA, SÓ EU TENHO")
newline()
    text_cut_scene(" CONDIÇÕES PARA POSSUIR")
newline()
    text_cut_scene(" AS JOIAS DO INFINITO. ")
newline()
    text_cut_scene(" ENTREGUEM TODAS OU EU")
newline()
    text_cut_scene("" MATAREI TODOS DA TERRA!"")
newline()
    text_cut_scene("PERCEBENDO A LOUCURA DE")
newline()
    text_cut_scene("THANOS PELO PODER, OS HERÓIS")
newline()
    text_cut_scene("DA TERRA, DECIDEM ENCONTRAR")
newline()
    text_cut_scene("AS TRÊS JOIAS RESTANTES.")
newline()
    text_cut_scene("O COMPUTADOR INDICOU QUATRO")
newline()
    text_cut_scene("NOVAS POSSÍVEIS LOCALIZAÇÕES.")
paragraph()
    text_cut_scene("1. EGITO, AO NORTE DO.")
newline()
    text_cut_scene("  CONTINENTE AFRICANO.")
newline()
    text_cut_scene("2. NO CINTURÃO DE ASTEROIDES.")
newline()
    text_cut_scene("3 COMPLEXO MINERADOR")
newline()
    text_cut_scene("  ABANDONADO NO ARIZONA.")
newline()
    text_cut_scene("4. MONTE VESÚVIO, ITÁLIA.")
endstring()
text_cut_scene_04:
    text_cut_scene("OS HERÓIS CONSEGUEM PEGAR")
newline()
    text_cut_scene("CINCO JOIAS DO INFINITO E")
newline()
    text_cut_scene("AGORA MIRAM A BASE DE THANOS.")
newline()
    text_cut_scene("ENQUANTO VIAJAM PARA O")
newline()
    text_cut_scene("SANTUÁRIO DE THANOS,")
newline()
    text_cut_scene("UMA MULHER APARECE.")
paragraph()
    DB $A8
    text_cut_scene("EU SOU NEBULOSA. VOCÊS")
newline()
    text_cut_scene(" SÃO OS QUE TENTAM")
newline()
    text_cut_scene(" ATRAPALHAR OS PLANOS DO")
newline()
    text_cut_scene(" MEU PAI? VOCÊS NÃO")
newline()
    text_cut_scene(" SERÃO PROBLEMAS PARA ELE.")
newline()
    text_cut_scene(" EU CUIDAREI DE VOCÊS!")
    DB $A8
endstring()
text_cut_scene_05:
    text_cut_scene("APÓS DERROTAR NEBULOSA,")
newline()
    text_cut_scene("THANOS FINALMENTE APARECE.")
newline()
    DB $A8
    text_cut_scene("ENTÃO... VOCÊS DERROTARAM")
newline()
    text_cut_scene(" MINHA FILHA, IMPRESSIONANTE.")
newline()
    text_cut_scene(" VOCÊS PARECEM DETERMINADOS A")
newline()
    text_cut_scene(" ATRAPALHAR MEUS PLANOS.")
newline()
    text_cut_scene(" ENTÃO IREI ACABAR COM TODOS")
newline()
    text_cut_scene(" VOCÊS, E PEGAREI AS JOIAS.")
newline()
    text_cut_scene(" EU SEREI UM DEUS ONIPOTENTE!")
newline()
    text_cut_scene(" PREPAREM-SE PARA A MORTE!")
    DB $A8
endstring()
text_cut_scene_06:
    text_cut_scene("THANOS FOI DERROTADO, O")
newline()
    text_cut_scene("UNIVERSO ESTÁ A SALVO AGORA.")
newline()
    text_cut_scene("ENQUANTO WARLOCK VÊ AS JOIAS,")
newline()
    text_cut_scene("ELE DIZ:")
newline()
    DB $A8
    text_cut_scene("OBRIGADO, HERÓIS. COM")
newline()
    text_cut_scene(" THANOS DERROTADO, AS JOIAS")
newline()
    text_cut_scene(" ESTARÃO SEGURAS COMIGO.")
newline()
    text_cut_scene(" TENHO CERTEZA QUE O UNIVERSO")
newline()
    text_cut_scene(" SEGUIRÁ SEU CURSO NATURAL.")
newline()
    text_cut_scene(" EU PROMETO A VOCÊS.")
newline()
    text_cut_scene(" USAREI AS JOIAS PARA O BEM")
newline()
    text_cut_scene(" DE TODOS.")
newline()
    text_cut_scene(" OBRIGADO, HERÓIS DA TERRA.")
    DB $A8
endstring()
text_cut_scene_07:
    text_cut_scene("OS HERÓIS VOLTAM PARA")
newline()
    text_cut_scene("CASA, DE VOLTA À TERRA,")
newline()
    text_cut_scene("ONDE FAMÍLIA E AMIGOS")
newline()
    text_cut_scene("OS ESPERAM. ")
newline()
    text_cut_scene("MAS SERÁ QUE O MUNDO")
newline()
    text_cut_scene("ESTARÁ REALMENTE A SALVO?")
endstring()
