origin $053DEE
text_intro_01:
    text_intro("JOIAS DO INFINITO.")
newline()
    text_intro("HÁ SEIS JOIAS DIFERENTES.")
newline()
    text_intro("CADA JOIA CONTROLA UMA")
newline()
    text_intro("DAS SEIS FORÇAS QUE SÃO,")
newline()
    text_intro("TEMPO, ESPAÇO, PODER,")
newline()
    text_intro("REALIDADE, MENTE OU ALMA.")
newline()
    text_intro("DIZEM QUE O SER QUE OBTER")
newline()
    text_intro("TODAS AS JOIAS SE TORNARÁ")
newline()
    text_intro("UM SER ONIPOTENTE --")
newline()
    text_intro("SOBERANO DE TODO UNIVERSO.")
paragraph()
     text_intro("ALGUÉM JÁ COMEÇOU A")
newline()
    text_intro(" REUNIR ESSAS JOIAS.")
newline()
    text_intro(" SE ELES CONSEGUIREM REUNIR")
newline()
    text_intro(" TODAS AS JOIAS, O UNIVERSO")
newline()
    text_intro(" SOFRERÁ UMA NOVA ERA DO MAL.")
newline()
    text_intro(" VOCÊ DEVE AJUDAR!")
newline()
    text_intro("É O PEDIDO DE ADAM WARLOCK")
newline()
    text_intro("AOS MAIORES HERÓIS DA TERRA.")
endstring()
    text_intro("SABENDO QUE O DESTINO DE")
newline()
    text_intro("TODO O UNIVERSO ESTÁ EM JOGO,")
newline()
    text_intro("OS HERÓIS MAIS PODEROSOS DA")
newline()
    text_intro("TERRA SE UNEM PARA AJUDAR")
newline()
    text_intro("ADAM WARLOCK A IMPEDIR QUE")
newline()
    text_intro("AS JOIAS DO INFINITO CAIAM")
newline()
    text_intro("EM MÃOS ERRADAS!")
endstring()

text_intro_02:
    text_intro("À MEDIDA QUE AS JOIAS DO")
newline()
    text_intro("INFINITO CAEM NA TERRA, A")
newline()
    text_intro("RAÇA HUMANA COMEÇA A")
newline()
    text_intro("PERCEBER QUE ESTÃO EM GRAVE")
newline()
    text_intro("PERIGO.")
newline()
    text_intro("OS HERÓIS, DETERMINADOS A")
newline()
    text_intro("AJUDAR ADAM WARLOCK, PARTEM")
newline()
    text_intro("EM BUSCA DAS JOIAS QUE FORAM")
newline()
    text_intro("ESPALHADAS PELO MUNDO.")
newline()
    text_intro("O SUPERCOMPUTADOR DA")
newline()
    text_intro("EMPRESA STARK INDICOU QUATRO")
newline()
    text_intro("LOCALIZAÇÕES ONDE QUE AS")
newline()
    text_intro("JOIAS DO INFINITO PODERIAM")
newline()
    text_intro("TER CAÍDO.")
paragraph()
    text_intro("1 PRÓXIMO AO CASTELO DO")
newline()
    text_intro("  DR. DESTINO NA LATVÉRIA.")
newline()
    text_intro("2 NA BACIA DO RIO AMAZONAS,")
newline()
    text_intro("  NA REGIÃO CENTRAL DA")
newline()
    text_intro("  AMÉRICA DO SUL.")
newline()
    text_intro("3 ALASCA, NA REGIÃO NORTE DA")
newline()
    text_intro("  AMÉRICA DO NORTE.")
newline()
    text_intro("4 NO AQUÁRIO DE BOSTON, NA")
newline()
    text_intro("  REGIÃO LESTE DA")
newline()
    text_intro("  AMÉRICA DO NORTE.")
paragraph()
    text_intro(""INVESTIGUEM ESTAS ÁREAS"")
newline()
    text_intro("" IMEDIATAMENTE!"")
endstring()    