origin $00054CA2
text_itens_01:
    text_itens("JOIA DO TEMPO:")
newline()
newline()
    text_itens(" DOMINA O TEMPO.")
newline()
    text_itens(" PERMITE SE MOVER")
newline()
    text_itens(" RAPIDAMENTE ATRAVÉS")
newline()
    text_itens(" DO FLUXO TEMPORAL.")

endstring()
text_itens_02: 
    text_itens("JOIA DA REALIDADE:")
newline()
newline()
    text_itens(" DOMINA A REALIDADE.")
newline()
    text_itens(" PERMITE ENCONTRAR")
newline()
    text_itens(" ITENS OCULTOS COM,")
newline()
    text_itens(" SUA PERCEPÇÃO ")
newline()
    text_itens(" AMPLIADA.")
endstring()
text_itens_03: 
    text_itens("JOIA DO PODER:")
newline()
newline()
    text_itens(" DOMINA O PODER.")
newline()
    text_itens(" AUMENTA SEU")
newline()
    text_itens(" PODER DE ATAQUE.")
endstring()
text_itens_04: 
    text_itens("JOIA DO ESPAÇO:")
newline()
newline()
    text_itens(" DOMINA O ESPAÇO.")
newline()
    text_itens(" PERMITE AO PORTADOR")
newline()
    text_itens(" PULAR MAIS ALTO,")
newline()
    text_itens(" CONTROLANDO A")
newline()
    text_itens(" GRAVIDADE.")
newline()
    text_itens(" FIELDS.")
endstring()
text_itens_05: 
    text_itens("JOIA DA ALMA:")
newline()
newline()
    text_itens(" DOMINA A ALMA.")
newline()
    text_itens(" AUMENTA A VIDA")
newline()
    text_itens(" MÁXIMA E PODE")
newline()
    text_itens(" EXTENDER A SUA")
newline()
    text_itens(" BARRA DE FORÇA")
newline()
    text_itens(" VITAL.")
endstring()
text_itens_06:
    text_itens("TANQUE DE ENERGIA PEQUENO:")
newline()
newline()
    text_itens(" RECUPERA A SUA ")
newline()
newline()
    text_itens(" SAÚDE EM 50%.")
endstring()
text_itens_07:
    text_itens("TANQUE DE ENERGIA GRANDE:")
newline()
newline()
    text_itens(" RESTAURA TODA A")
newline()
newline()
    text_itens(" SUA SAÚDE.")
endstring()
text_itens_08:
    text_itens("ITEM JOIA DO PODER:")
newline()
newline()
    text_itens(" AO EXECUTAR ESSA JOIA")
newline()
newline()
    text_itens(" PERMITE AO PORTADOR")
newline()
newline()
    text_itens(" EXECUTAR MOVIMENTOS ESPECIAL.")
endstring()
text_itens_09:
    text_itens("ITEM DE REVIVER:")
newline()
newline()
    text_itens(" PERMITE QUE VOCÊ")
newline()
newline()
    text_itens(" REVIVA O SEU")
newline()
newline()
    text_itens(" PERSONAGEM.")
endstring()
