origin $000EF30F
text_locais_01:
    text_locais(" ($00)BASE VINGADORES")
endstring1()
endstring1()
    text_locais("($00)ESSE É O LOCAL ($41)")
newpage1()
endstring1()
    text_locais("($00)DE TREINAMENTO")
newpage1()
endstring1()
    text_locais("($00)E O SISTEMA PARA")
newpage1()
endstring1()
    text_locais("($00)USAR AS SENHAS.")
endstring1()
endstring1()
origin $000EF393
text_locais_02:
    text_locais("   ($00)CASTELO DO($53)")
newpage1()
endstring1()
    text_locais("   ($00)DOUTOR DESTINO")
endstring1()
endstring1()
    text_locais("($00)CASTELO DO DESTINO - -")
newpage1()
endstring1()
    text_locais("($00)SOB O DOMÍNIO DO")
newpage1()
endstring1()
    text_locais("($00)BRILHANTE E PERVERSO")
newpage1()
endstring1()
    text_locais("($00)CIENTISTA MAIS")
newpage1()
endstring1()
    text_locais("($00)CONHECIDO COMO")
newpage1()
endstring1()
    text_locais("($00)VICTOR VON DOOM.")
endstring1()
endstring1()

origin $000EF467
text_locais_03:
    text_locais("   ($00)AMAZÔNIA")
endstring1()
endstring1()
    text_locais("($00)NAS RUÍNAS ANTIGAS,")
newpage1()
endstring1()
    text_locais("($00)LOCALIZADA NAS")
newpage1()
endstring1()
    text_locais("($00)PROFUNDAS DAS SELVAS")
newpage1()
endstring1()
    text_locais("($00)DO BRASIL.")
endstring1()
endstring1()
origin $000EF4EF
text_locais_04:
    text_locais("    ($00)ALASCA")
endstring1()
endstring1()
    text_locais("($00)AS MONTANHAS")
newpage1()
endstring1()
    text_locais("($00)EXTREMAMENTE FRIAS")
newpage1()
endstring1()
    text_locais("($00)DO ALASCA ONDE")
newpage1()
endstring1()
    text_locais("($00)ATÉ O SOLO")
newpage1()
endstring1()
    text_locais("($00)ESTÁ CONGELADO.")
endstring1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais("($00)AQUÁRIO DE BOSTON")
endstring1()
endstring1()
    text_locais("($00)UM AQUÁRIO LOCALIZADO")
newpage1()
endstring1()
    text_locais("($00)NO LADO LESTE AMERICANO")
newpage1()
endstring1()
    text_locais("($00)ONDE POSSIVELMENTE")
newpage1()
endstring1()
    text_locais("($00)UMA DAS JOIAS PODERIA")
newpage1()
endstring1()
    text_locais("($00)TER CAÍDO.")
newpage1()
endstring1()
    text_locais("($00) ")
endstring1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais("   ($00)EGITO")
endstring1()
endstring1()
    text_locais("($00)ANTIGAS PIRÂMIDES")
newpage1()
endstring1()
    text_locais("($00)QUE SE ERGUEM DOS")
newpage1()
endstring1()
    text_locais("($00)DESERTOS VARRIDOS")
newpage1()
endstring1()
    text_locais("($00)PELO VENTO.")
endstring1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais(" ($00)MONTE VESÚVIU")
endstring1()
endstring1()
    text_locais("($00)UM VULCÃO GIGANTE")
newpage1()
endstring1()
    text_locais("($00)CHEIO DE LAVA")
newpage1()
endstring1()
    text_locais("($00)INCANDESCENTE.")
endstring1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais(" ($00)COMPLEXO DE MINERAÇÃO")
newpage1()
endstring1()
    text_locais("   ($00)DO ARIZONA")
endstring1()
endstring1()
    text_locais("($00)UMA BASE ")
newpage1()
endstring1()
    text_locais("($00)AMERICANA INVADIDA")
newpage1()
endstring1()
    text_locais("($00)E ASSOMBRADA")
newpage1()
endstring1()
    text_locais("($00)PELO MAL.")
endstring1()
 endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais(" ($00)CINTURÃO DE ASTEROIDES")
endstring1()
endstring1()
    text_locais("($00)UM CEMITÉRIO")
newpage1()
endstring1()
    text_locais("($00)ESPACIAL ONDE")
newpage1()
endstring1()
    text_locais("($00)O SILÊNCIO REINA.")
endstring1()
endstring1()
