origin $00054A36
            text_menu("MODO DE OPÇÕES")
        newline()
        newline()
        
         newline()
         newline()
            text_menu(" ")
         newline()
            text_menu(" SOM          ($FE)3 ESTÉREO ($FE) ")
        newline()
        newline()
        newline()
            text_menu(" TESTE DE BGM        ($FE)300($FE) ")
        newline()
        newline()
        newline()
            text_menu(" TESTE E S           ($FE)300($FE) ")
        newline()
        newline()
        newline()
            text_menu(" CONFIGURAÇÕES          ($FE)3($5C)($6B)($92)($63)($FE) ")
        newline()
        newline()
        newline()
         text_menu("                     ($FE)3($CA)($8F)($89)($E0)($FE) ")
        newline()
        newline()
            text_menu(" SAIR")
        endstring()