origin $00054A36
    db $FB
    db $A2
    db $FB
    text_profile("PERFIL DOS HERÓIS")
endstring()
    text_profie("NOME REAL:")
endstring()
    text_profile("ALTURA:")
endstring()
    text_profile("PESO:")
endstring()
    text_profile("APELIDO:")
endstring()
    text_profile("ARMA & PODERES:")
endstring()
    text_profile("TRAÇOS DO PERSONAGEM:")
endstring()
    text_profile("ANTHONY "TONY"")
newline()
    text_profile("STARK")
endstring()
    text_profile("1,85M")
endstring()
    text_profile("192KG")
endstring()
    text_profile("CABEÇA DE LATA, O")
newline()
    text_profile("VINGADOR DOURADO")
endstring()
    text_profile("USANDO UMA ARMADURA DE ALTA")
    text_profile("TECNOLOGIA, ELE LUTA COM")
    text_profile("UM VASTO CONJUNTO DE ARMAS.")
endstring()
    text_profile("UM SUPER-HERÓI QUE COMBATE")
    text_profile("O MAL EM SUA ARMADURA")
    text_profile("INVENTADA POR ELE MESMO.")
endstring()
    text_profile("DR'ROBERT BRUCE")
    db $FC
    db $FC
    db $FC
    text_profile("BANNER")
endstring()
    text_profile("2,28M")
endstring()
    text_profile("472KG")
endstring()
    text_profile("BRUCIE")
endstring()
    text_profile("UM GIGANTE VERDE CUJA A FORÇA")
    text_profile("É QUASE INSUPERÁVEL. ELE PODE JOGAR")
    text_profile("UM TANQUE COM A MESMA FACILIDADE QUE")
    text_profile("UM HUMANO ARREMESSA UMA BOLA DE BASEBOL.")
endstring()
    text_profile("COM O CÉREBRO DE UM SUPER")
    text_profile("GÊNIO E A FORÇA DE")
    text_profile("UM TITÃ, SUA AVERSÃO À")
    text_profile("INJUSTIÇA É INCOMPARÁVEL.")
endstring()
    text_profile("LOGAN")
endstring()
    text_profile("1,60M")
endstring()
    text_profile(" 88KG")
endstring()
    text_profile("CARCAJU")
endstring()
    text_profile("ELE ATACA QUALQUER OPONENTE")
    text_profile("COM FEROCIDADE ANIMAL, USANDO")
    text_profile("SUAS GARRAS DE ADAMANTIUM")
    text_profile("INDESTRUTÍVEIS.")
endstring()
    text_profile("COMO UM MEMBRO CHAVE DOS")
    text_profile("X-MEN, ELE É UM GUERREIRO")
    text_profile("IMPULSIVO QUE ESTÁ SEMPRE")
    text_profile("EM BUSCA DE UMA BOA BRIGA.")
endstring()
    text_profile("STEVE ROGERS")
endstring()
    text_profile("1,87M")
endstring()
    text_profile("108KG")
endstring()
    text_profile("CAP")
newline()
    text_profile("SENTINELA DA LIBERDADE")
endstring()
    text_profile("ELE COMBATE O MAL, EQUIPADO")
    text_profile("COM UM ESCUDO FEITO DE")
    text_profile("UMA LIGA DE ADAMANTIUM.")
endstring()
    text_profile("ELE É O LÍDER DOS")
    text_profile("VINGADORES E ESTARIA")
    text_profile("DISPOSTO A SACRIFICAR")
    text_profile("SUA VIDA PELA LIBERDADE")
    text_profile("E PELA JUSTIÇA.")
endstring()
    text_profile("PETER PARKER")
endstring()
    text_profile("1,77M")
endstring()
    text_profile(" 74KG")
endstring()
    db $FC
    db $FC
    db $FC
    db $FC
    db $FC
    db $FC
    text_profile("SPIDEY,")
newline()
    text_profile("O LANÇA TEIAS")
endstring()
    text_profile("ELE COMBATE O CRIME COM SUAS")
    text_profile("HABILIDADES ÚNICAS SEMELHANTES")
    text_profile("ÀS DE UMA ARANHA E CRIA TEIAS")
    text_profile("COM SEU LANÇADOR DE TEIAS.")
endstring()
    text_profile("UM SUPER HERÓI QUE LUTA COM")
    text_profile("A RESPONSABILIDADE DE UM HOMEM")
    text_profile("E PELO AMOR DE SUA ESPOSA")
    text_profile("MARY JANE.")
endstring()
