vs_mode_configuration:
    gameText("                Opções de Combate")
 newline()
    gameText("                  ..........Ki..........")
 newline()
    gameText("              (UP/DOWN) ......Ataque...... (UP/DOWN)")
 newline()
    gameText("                (UP/DOWN) .....Defesa..... (UP/DOWN)")
 newline()
    gameText("Nível do Computador...........")
 newline()
    gameText("Trilha Sonora.......")
 endstring()
 vsOptionOne()
 vsOptionTwo()
 vsOptionThree()
 vsOptionFour()
 vsOptionFive()
 vsOptionSix()
 endstring()
 endstring()