text_character_01:
    text_character("FREEDOM, LIBERTY, EQUALITY!")
paragraph()
    text_character("I'LL STOP ANYONE WHO TRIES")
paragraph()
    text_character("TO CRUSH THOSE BELIEFS!")
endstring()
text_ha_XX:
    text_character("ROOKIE! WHAT'D I TELL YA")
paragraph()
    text_character("BUB? I'M THE BEST THERE IS")
paragraph()
    text_character("AT WHAT I DO.")
endstring()
text_ha_XX:
    text_character("THANK GOODNESS! THERE IS")
paragraph()
    text_character("ALMOST NO DAMAGE TO MY")
paragraph()
    text_character("RUNNING SYSTEMS.")
paragraph()
    text_character("NOW, LET'S MOVE!")
endstring()
text_ha_XX:
    text_character("DID YOU TRULY BELIEVE YOU")
paragraph()
    text_character("COULD BEAT ME WITH MUSCLE?")
paragraph()
    text_character("WE COULD HAVE TALKED...")
paragraph()
    text_character("USE YOUR BRAIN! ")
endstring()
text_character_XX:
    text_character("OK, SO WHERE ARE WE GOING")
paragraph()
    text_character("NEXT?")
paragraph()
    text_character("I'M READY FOR ANYBODY!")
endstring()

