
text_game:
    text_game("AS THE INFINITY GEMS FALL TO")
newline()
    text_game("THE EARTH, THE HUMAN RACE")
newline()
    text_game("BEGINS TO REALIZE THAT IT IS")
newline()
    text_game("IN GRAVE DANGER. THE HEROES,")
newline()
    text_game("DETERMINED TO ASSIST")
newline()
    text_game("ADAM WARLOCK, BEGAN TO SEARCH")
newline()
    text_game("FOR THE GEMS THAT HAVE BEEN")
newline()
    text_game("SCATTERED OVER THE WORLD.")
newline()
    text_game("STARK ENTERPRISE'S")
newline()
    text_game("SUPER COMPUTER HAS POINTED")
newline()
    text_game("OUT FOUR LOCATIONS WHERE")
newline()
    text_game("THE INFINITY GEMS MAY HAVE")
newline()
    text_game("LANDED.")
newline()
newline()
    text_game("1 NEAR DR.DOOM'S CASTLE IN")
newline()
    text_game("  LATVERIA.")
newline()
    text_game("2 THE AMAZON RIVER BASIN IN")
newline()
    text_game("  THE CENTRAL REGION OF")
newline()
    text_game("  SOUTH AMERICA.")
newline()
    text_game("3 ALASKA, IN THE NORTHERN")
newline()
    text_game("  REGION OF NORTH AMERICA.")
newline()
    text_game("4 THE BOSTON AQUARIUM IN THE")
newline()
    text_game("  EASTERN AREA OF")
newline()
    text_game("  NORTH AMERICA.")
newline()
newline()
    text_game(""INVESTIGATE THESE AREAS"")
newline()
    text_game("" IMMEDIATELY!"")
endstring()

text_game:
    text_game("AFTER OBTAINING THE SECOND")
newline()
    text_game("GEM, OUR HEROES HAVE LEARNED")
newline()
    text_game("SOME VALUABLE INFORMATION.")
newline()
    text_game("THE ENEMY'S NAME IS THE MAGUS.")
newline()
    text_game("HE IS GATHERING THE GEMS AND")
newline()
    text_game("USING A HUGE ORBITING")
newline()
    text_game("BATTLESHIP AS HIS BASE.")
newline()
    text_game("THE UNIVERSE WILL NEVER BE")
newline()
    text_game("SAFE UNTIL THE MAGUS IS")
newline()
    text_game("DEFEATED.")
newline()
    text_game("WITH THAT IN MIND, THE HEROES")
newline()
    text_game("DECIDED TO CHARGE THE")
newline()
    text_game("ORBITING SPACECRAFT.")
endstring()

text_game:
    text_game("THE HEROES HAVE FINALLY")
newline()
    text_game("DEFEATED THE MAGUS. HOWEVER,")
newline()
    text_game("THE MAGUS ONLY HAD ONE OF")
newline()
    text_game("THE GEMS. AT THAT MOMENT,")
newline()
    text_game("A MESSAGE APPEARED ON")
newline()
    text_game("THE COMPUTER SCREEN.")
newline()
    text_game(""I AM THANOS. HEAR ME HEROES")
newline()
    text_game(" OF EARTH, ONLY I AM")
newline()
    text_game(" QUALIFIED TO POSSESS")
newline()
    text_game(" THE INFINITY GEMS.")
newline()
    text_game(" GIVE ME THE GEMS OR")
newline()
    text_game(" YOU SHALL DIE!"")
newline()
    text_game("REALIZING THAT THANOS IS MAD")
newline()
    text_game("WITH POWER, THE HEROES")
newline()
    text_game("OF EARTH DECIDED TO FIND")
newline()
    text_game("THE REMAINING THREE GEMS.")
newline()
    text_game("THE COMPUTER HAS POINTED OUT")
newline()
    text_game("FOUR NEW POSSIBLE LOCATIONS.")
newline()
newline()
    text_game("1 EGYPT IN THE NORTH OF")
newline()
    text_game("  AFRICAN CONTINENT.")
newline()
    text_game("2 ASTEROID BELT.")
newline()
    text_game("3 AN ABANDONED MINING")
newline()
    text_game("  COMPLEX IN ARIZONA.")
newline()
    text_game("4 MT.VESUVIUS,ITALY.")
endstring()

text_game:
    text_game("THE HEROES HAVE COLLECTED")
newline()
    text_game("FIVE OF THE INFINITY GEMS AND")
newline()
    text_game("HAVE NOW TARGETED THANOS'S")
newline()
    text_game("BASE.  AS THE HEROES TRAVEL")
newline()
    text_game("INTO THANOS'S SHRINE,")
newline()
    text_game("A WOMAN APPEARS.")
newline()
newline()
    text_game(""I AM NEBULA. SO YOU'RE")
newline()
    text_game(" THE ONES WHO SEEK TO")
newline()
    text_game(" INTERFERE WITH MY MASTER")
newline()
    text_game(" THANOS? THERE IS NO REASON")
newline()
    text_game(" FOR THANOS TO BE TROUBLED BY")
newline()
    text_game(" YOU. I SHALL DEAL WITH YOU!"")
endstring()

text_game:
    text_game("AFTER DEFEATING NEBULA,")
newline()
    text_game("THANOS FINALLY APPEARS.")
newline()
    text_game(""SO... YOU'VE DEFEATED NEBULA.")
newline()
    text_game(" IMPRESSIVE. YOU SEEM TO BE")
newline()
    text_game(" DETERMINED TO INTERFERE")
newline()
    text_game(" WITH ME. I WILL DESTROY YOU")
newline()
    text_game(" AND OBTAIN THE GEMS AND")
newline()
    text_game(" BECOME OMNIPOTENT.")
newline()
    text_game(" PREPARE TO MEET YOUR DEATH!"")
endstring()

text_game:
    text_game("THANOS HAS BEEN DEFEATED,")
newline()
    text_game("NOW THE UNIVERSE IS SAFE.")
newline()
    text_game("AS WARLOCK LOOKS AT THE GEMS")
newline()
    text_game("HE SAYS,")
newline()
    text_game(""THANK YOU HEROES. WITH")
newline()
    text_game(" THANOS GONE,THE GEMS WILL BE")
newline()
    text_game(" SAFE IN MY HANDS. I'M SURE")
newline()
    text_game(" THAT THE UNIVERSE WILL")
newline()
    text_game(" CONTINUE ON ITS NATURAL")
newline()
    text_game(" COURSE.  I PROMISE TO YOU.")
newline()
    text_game(" I'LL USE THE GEMS TO BENEFIT")
newline()
    text_game(" EVERYONE.")
newline()
    text_game(" THANK YOU, WORLD HEROES."")
endstring()

text_game:
    text_game("THE HEROES MAKE THEIR WAY")
newline()
    text_game("HOME BACK TO EARTH,")
newline()
    text_game("WHERE THEIR FAMILY AND")
newline()
    text_game("FRIENDS AWAIT.")
newline()
    text_game("WILL THE WORLD EVER TRULY")
newline()
    text_game("BE SAFE?")
endstring()

