
text_itens:
    text_itens("JOIA DO TEMPO:")
newline()
newline()
    text_itens(" DOMINA O TEMPO.")
newline()
    text_itens(" PERMITE SE MOVER")
newline()
    text_itens(" RAPIDAMENTE ATRAVÉS")
newline()
    text_itens(" DO FLUXO TEMPORAL.")
newline()
    text_itens(" THE TIME STREAM.")
endstring()
text_itens: 
    text_itens("REALITY GEM:")
newline()
newline()
    text_itens(" RULES REALITY.")
newline()
    text_itens(" ENABLES YOU TO")
newline()
    text_itens(" FIND HIDDEN ITEMS,")
newline()
    text_itens(" WITH YOUR EXPANDED")
newline()
    text_itens(" PERCEPTIONS.")
endstring()
text_itens: 
    text_itens("POWER GEM:")
newline()
newline()
    text_itens(" RULES POWER.")
newline()
    text_itens(" INCREASES YOUR")
newline()
    text_itens(" ATTACKING POWER.")
endstring()
text_itens: 
    text_itens("SPACE GEM:")
newline()
newline()
    text_itens(" RULES SPACE.")
newline()
    text_itens(" ENABLES YOU TO")
newline()
    text_itens(" JUMP HIGHER,")
newline()
    text_itens(" ALTERING")
newline()
    text_itens(" GRAVITATIONAL")
newline()
    text_itens(" FIELDS.")
endstring()
text_itens: 
    text_itens("SOUL GEM:")
newline()
newline()
    text_itens(" RULES SOUL.")
newline()
    text_itens(" INCREASES MAXIMUM")
newline()
    text_itens(" AMOUNT OF VITALITY,")
newline()
    text_itens(" EXTENDING AND")
newline()
    text_itens(" INCREASING YOUR")
newline()
    text_itens(" LIFE FORCE.")
endstring()
text_itens:
    text_itens("SMALL ENERGY TANK:")
newline()
newline()
    text_itens(" RECOVERS YOUR")
newline()
newline()
    text_itens(" VITALITY BY 50%.")
endstring()
text_itens:
    text_itens("BIG ENERGY TANK:")
newline()
newline()
    text_itens(" RESTORES ALL OF")
newline()
newline()
    text_itens(" YOUR VITALITY.")
endstring()
text_itens:
    text_itens("GEM POWER ITEM:")
newline()
newline()
    text_itens(" ENABLES YOU TO")
newline()
newline()
    text_itens(" EXECUTE A GEM")
newline()
newline()
    text_itens(" SPECIAL MOVE ONCE.")
endstring()
text_itens:
    text_itens("REVIVE ITEM:")
newline()
newline()
    text_itens(" ENABLES YOU TO")
newline()
newline()
    text_itens(" REVIVE YOUR")
newline()
newline()
    text_itens(" CHARACTER.")
endstring()
