
origin $000EF30F
text_locais_01:
    text_locais(" ($00)AVENGERS BASE")
endstring1()
endstring1()
    text_locais("($00)THERE IS ($41)")
newpage1()
endstring1()
    text_locais("($00)TRAINING ROOM")
newpage1()
endstring1()
    text_locais("($00)AND A PASSWORD")
newpage1()
endstring1()
    text_locais("($00)SYSTEM($2E)")
endstring1()
endstring1()
origin $000EF393
text_locais_02:
    text_locais("   ($00)DR.DOOM'($53)")
newpage1()
endstring1()
    text_locais("     ($00)CASTLE")
endstring1()
endstring1()
    text_locais("($00)CASTLE DOOM ($2D)($00)($2D)")
newpage1()
endstring1()
    text_locais("($00)RULED B($59)")
newpage1()
endstring1()
    text_locais("($00)THE BRILLIANT")
newpage1()
endstring1()
    text_locais("($00)AND TWISTED")
newpage1()
endstring1()
    text_locais("($00)SCIENTIST KNOW($4E)")
newpage1()
endstring1()
    text_locais("($00)AS DR.DOOM($2E)")
endstring1()
endstring1()

origin $000EF467
text_locais_03:
    text_locais("    ($00)AMAZO($4E)")
endstring1()
endstring1()
    text_locais("($00)ANCIENT RUINS,")
newpage1()
endstring1()
    text_locais("($00)LOCATED DEE($50)")
newpage1()
endstring1()
    text_locais("($00)IN THE JUNGLE($53)")
newpage1()
endstring1()
    text_locais("($00)OF BRAZIL($2E)")
endstring1()
endstring1()
origin $000EF4EF
text_locais_04:
    text_locais("    ($00)ALASK($41)")
endstring1()
endstring1()
    text_locais("($00)THE SEVEREL($59)")
newpage1()
endstring1()
    text_locais("($00)COLD ALASKA($4E)")
newpage1()
endstring1()
    text_locais("($00)MOUNTAINS WHERE")
newpage1()
endstring1()
    text_locais("($00)EVEN THE GROUND")
newpage1()
endstring1()
    text_locais("($00)IS FROZEN($2E)")
endstring1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais("($00)BOSTON AQUARIUM")
endstring1()
endstring1()
    text_locais("($00)AN EASTER($4E)")
newpage1()
endstring1()
    text_locais("($00)AMERICA($4E)")
newpage1()
endstring1()
    text_locais("($00)AQUARIUM")
newpage1()
endstring1()
    text_locais("($00)WHERE ONE O($46)")
newpage1()
endstring1()
    text_locais("($00)THE GEMS MA($59)")
newpage1()
endstring1()
    text_locais("($00)HAVE LANDED($2E)")
endstring1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais("   ($00)EGYPT")
endstring1()
endstring1()
    text_locais("($00)ANCIENT PYRAMID($53)")
newpage1()
endstring1()
    text_locais("($00)WHICH RISE FROM")
newpage1()
endstring1()
    text_locais("($00)THE WIND($2D)($00)SWEPT")
newpage1()
endstring1()
    text_locais("($00)DESERTS($2E)")
endstring1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais(" ($00)MT.VESUVIU($53)")
endstring1()
endstring1()
    text_locais("($00)A GIANT VOLCAN($4F)")
newpage1()
endstring1()
    text_locais("($00)FILLED WIT($48)")
newpage1()
endstring1()
    text_locais("($00)RED($2D)($00)HOT LAVA($2E)")
endstring1()
endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais(" ($00)ARIZONA MININ($47)")
newpage1()
endstring1()
    text_locais("    ($00)COMPLE($58)")
endstring1()
endstring1()
    text_locais("($00)AN AMERICA($4E)")
newpage1()
endstring1()
    text_locais("($00)BASE INVADED")
newpage1()
endstring1()
    text_locais("($00)AND HAUNTED")
newpage1()
endstring1()
    text_locais("($00)BY THE EVIL($2E)")
endstring1()
 endstring1()
newpage1()
endstring1()
newpage1()
endstring1()
    text_locais(" ($00)ASTEROID BELT")
endstring1()
endstring1()
    text_locais("($00)A SPACE")
newpage1()
endstring1()
    text_locais("($00)GRAVEYARD WHERE")
newpage1()
endstring1()
    text_locais("($00)SILENCE RULES($2E)")
endstring1()
endstring1()
