
            text_menu("OPTION MODE")
        newline()
        newline()
        
         newline()
         newline()
            text_menu(" ")
         newline()
            text_menu(" SOUND           ($FE)3 STEREO ($FE) ")
        newline()
        newline()
        newline()
            text_menu(" BGM TEST           ($FE)300($FE) ")
        newline()
        newline()
        newline()
            text_menu(" S E TEST           ($FE)300($FE) ")
        newline()
        newline()
        newline()
            text_menu(" KEY CONFIG          ($FE)3($5C)($6B)($92)($63)($FE) ")
        newline()
        newline()
        newline()
         text_menu("                     ($FE)3($CA)($8F)($89)($E0)($FE) ")
        newline()
        newline()
            text_menu(" EXIT")
        endstring()