origin $00054A36
    db $FB
    db $A2
    db $FB
    text_profile("PLAYER PROFILE")

endstring()
    text_profie("REAL NAME:")

endstring()
    text_profile("HEIGHT:")

endstring()
    text_profile("WEIGHT:")

endstring()
    text_profile("NICK NAME:")
endstring()
    text_profile("WEAPON&POWER:")
endstring()
    text_profile("CHARACTER TRAITS:")
endstring()
    text_profile("ANTHONY "TONY"")
    text_profile("STARK")
endstring()
    text_profile("185CM")
endstring()
    text_profile("192KG")
endstring()
    text_profile("SHELLHEAD,THE")
    text_profile("GOLDEN AVENGER")
endstring()
    text_profile("WEARING HIGH-TECH ARMOR,")
    text_profile("HE FIGHTS WITH A")
    text_profile("VAST ARRAY OF WEAPONS'")
endstring()
    text_profile("A SUPER HERO WHO BATTLES")
    text_profile("AGAINST EVIL IN HIS")
    text_profile("SELF-INVENTED ARMOR'")
endstring()
    text_profile("DR'ROBERT BRUCE")
    db $FC
    db $FC
    db $FC
    text_profile("BANNER")
endstring()
    text_profile("228CM")
endstring()
    text_profile("472KG")
endstring()
    text_profile("BRUCIE")
endstring()
    text_profile("A GREEN GIANT WHOSE STRENGTH")
    text_profile("IS ALMOST UNEQUALED' HE CAN")
    text_profile("THROW A TANK AS EASILY AS A")
    text_profile("HUMAN THROWS A BASEBALL'")
endstring()
    text_profile("WITH THE BRAIN OF A SUPER")
    text_profile("GENIUS AND THE BRAWN OF")
    text_profile("TITAN, HIS HATRED FOR")
    text_profile("INJUSTICE IS SECOND TO NONE'")
endstring()
    text_profile("LOGAN")
endstring()
    text_profile("160CM")
endstring()
    text_profile(" 88KG")
endstring()
    text_profile("WOLVIE")
endstring()
    text_profile("HE SLASHES ANY OPPONENT")
    text_profile("WITH ANIMAL FEROCITY,")
    text_profile("BY USING HIS UNBREAKABLE")
    text_profile("ADAMANTIUM CLAWS'")
endstring()
    text_profile("AS A KEY MEMBER OF THE")
    text_profile("X-MEN, HE%S A HOT-BLOODED")
    text_profile("WARRIOR WHO%S ALWAYS")
    text_profile("LOOKING FOR A GOOD BATTLE'")
endstring()
    text_profile("STEVE ROGERS")
endstring()
    text_profile("187CM")
endstring()
    text_profile("108KG")
endstring()
    text_profile("CAP, WING-HEAD")
endstring()
    text_profile("HE FIGHTS EVIL, EQUIPPED")
    text_profile("WITH A SHIELD MADE OF")
    text_profile("AN ADAMANTIUM-ALLOY'")
endstring()
    text_profile("HE IS THE LEADER OF")
    text_profile("THE AVENGERS, AND WOULD")
    text_profile("WILLINGLY LAY DOWN HIS")
    text_profile("LIFE FOR FREEDOM")
    text_profile("AND LIBERTY'")
endstring()
    text_profile("PETER PARKER")
endstring()
    text_profile("177CM")
endstring()
    text_profile(" 74KG")
endstring()
    db $FC
    db $FC
    db $FC
    db $FC
    db $FC
    db $FC
    text_profile("SPIDEY,")
    text_profile("THE WEB-SLINGER")
endstring()
    text_profile("HE BATTLES CRIME WITH")
    text_profile("HIS UNIQUE SPIDER-LIKE")
    text_profile("ABILITIES AND CREATES WEBS")
    text_profile("WITH HIS WEB-SHOOTER'")
endstring()
    text_profile("A SUPER HERO WHO FIGHTS FOR")
    text_profile("THE RESPONSIBILITY OF MAN")
    text_profile("AND FOR THE LOVE OF")
    text_profile("HIS WIFE, MARY JANE'")
endstring()
